{
  "openapi": "3.0.0",
  "info": {
    "description": "Specification of the Socket API endpoints",
    "title": "API Endpoints",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "https://api.socket.dev/v0"
    }
  ],
  "components": {
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "paths": {
    "/purl": {
      "post": {
        "tags": [
          "Packages"
        ],
        "summary": "Get Packages (Beta)",
        "operationId": "batchPackageFetch",
        "security": [
          {
            "basicAuth": [
              "packages:list"
            ]
          }
        ],
        "description": "Batch retrieval of package metadata and alerts by PURL strings. Compatible witch CycloneDX reports.\n\nPackage URLs (PURLs) are an ecosystem agnostic way to identify packages.\nCycloneDX SBOMs use the purl format to identify components.\nThis endpoint supports fetching metadata and alerts for multiple packages at once by passing an array of purl strings, or by passing an entire CycloneDX report.\n\nMore information on purl and CycloneDX:\n\n- [`purl` Spec](https://github.[...]"
      }
    },
    "/orgs/{org_slug}/audit-log": {
      "get": {
        "tags": [
          "Audit Log"
        ],
        "summary": "Get Audit Log Events",
        "operationId": "getAuditLogEvents",
        "security": [
          {
            "basicAuth": [
              "audit-log:list"
            ]
          }
        ],
        "description": "Paginated list of audit log events.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- audit-log:list"
      }
    },
    "/orgs/{org_slug}/export/cdx/{id}": {
      "get": {
        "tags": [
          "Export"
        ],
        "summary": "Export CycloneDX SBOM (Beta)",
        "operationId": "exportCDX",
        "security": [
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "Export a Socket SBOM as a CycloneDX SBOM\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:read"
      }
    },
    "/orgs/{org_slug}/export/spdx/{id}": {
      "get": {
        "tags": [
          "Export"
        ],
        "summary": "Export SPDX SBOM (Beta)",
        "operationId": "exportSPDX",
        "security": [
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "Export a Socket SBOM as a SPDX SBOM\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:read"
      }
    },
    "/orgs/{org_slug}/full-scans": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "List full scans",
        "operationId": "getOrgFullScanList",
        "security": [
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Returns a paginated list of all full scans in an org, excluding SBOM artifacts.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      },
      "post": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Create full scan",
        "operationId": "CreateOrgFullScan",
        "security": [
          {
            "basicAuth": [
              "full-scans:create"
            ]
          }
        ],
        "description": "Create a full scan from a set of package manifest files. Returns a full scan including all SBOM artifacts.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:create"
      }
    },
    "/orgs/{org_slug}/full-scans/{full_scan_id}": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Stream full scan",
        "operationId": "getOrgFullScan",
        "security": [
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Stream all SBOM artifacts for a full scan.\n\nThis endpoint returns the latest, available alert data for artifacts in the full scan (stale while revalidate).\nActively running analysis will be returned when available on subsequent runs.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      },
      "delete": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Delete full scan",
        "operationId": "deleteOrgFullScan",
        "security": [
          {
            "basicAuth": [
              "full-scans:delete"
            ]
          }
        ],
        "description": "Delete an existing full scan.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:delete"
      }
    },
    "/orgs/{org_slug}/full-scans/{full_scan_id}/metadata": {
      "get": {
        "tags": [
          "Full Scans"
        ],
        "summary": "Get full scan metadata",
        "operationId": "getOrgFullScanMetadata",
        "security": [
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Get metadata for a single full scan\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- full-scans:list"
      }
    },
    "/orgs/{org_slug}/repos": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "summary": "List repositories",
        "operationId": "getOrgRepoList",
        "security": [
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Lists repositories for the specified organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:list"
      },
      "post": {
        "tags": [
          "Repositories"
        ],
        "summary": "Create repository",
        "operationId": "createOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:create"
            ]
          }
        ],
        "description": "Create a repository.\n\nRepos collect Full scans and Diff scans and are typically associated with a git repo.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:create"
      }
    },
    "/orgs/{org_slug}/repos/{repo_slug}": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "summary": "Get repository",
        "operationId": "getOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Retrieve a repository associated with an organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:list"
      },
      "post": {
        "tags": [
          "Repositories"
        ],
        "summary": "Update repository",
        "operationId": "updateOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:update"
            ]
          }
        ],
        "description": "Update details of an existing repository.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:update"
      },
      "delete": {
        "tags": [
          "Repositories"
        ],
        "summary": "Delete repository",
        "operationId": "deleteOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:delete"
            ]
          }
        ],
        "description": "Delete a single repository and all of its associated Full scans and Diff scans.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:delete"
      }
    },
    "/analytics/org/{filter}": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get organization analytics (unstable)",
        "operationId": "getOrgAnalytics",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Get analytics data regarding the number of alerts found across all active repositories.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:write"
      }
    },
    "/analytics/repo/{name}/{filter}": {
      "get": {
        "tags": [
          "Analytics"
        ],
        "summary": "Get repository analytics",
        "operationId": "getRepoAnalytics",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Get analytics data regarding the number of alerts found in a single repository.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:write"
      }
    },
    "/dependencies/search": {
      "post": {
        "tags": [
          "Dependencies"
        ],
        "summary": "Search dependencies",
        "operationId": "searchDependencies",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Search for any dependency that is being used in your organization.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- Any"
      }
    },
    "/dependencies/upload": {
      "post": {
        "tags": [
          "Dependencies"
        ],
        "summary": "Create a snapshot of all dependencies from manifest information",
        "operationId": "createDependenciesSnapshot",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Upload a set of manifest or lockfiles to get your dependency tree analyzed by Socket.\nYou can upload multiple lockfiles in the same request, but each filename must be unique.\n\nThe name of the file must be in the supported list.\n\nFor example, these are valid filenames: \"requirements.txt\", \"package.json\", \"folder/package.json\", and \"deep/nested/folder/package.json\".\n\nThis endpoint consumes 100 units of your quota.\n\nThis endpoint requires the following org t[...]"
      }
    },
    "/report/supported": {
      "get": {
        "tags": [
          "Project Reports"
        ],
        "summary": "Get supported files for report",
        "operationId": "getReportSupportedFiles",
        "security": [
          {}
        ],
        "description": "Get a list of supported files for project report generation.\nFiles are categorized first by environment (e.g. NPM or PyPI), then by name.\n\nFiles whose names match the patterns returned by this endpoint can be uploaded for report generation.\nExamples of supported filenames include `package.json`, `package-lock.json`, and `yarn.lock`.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:"
      }
    },
    "/report/delete/{id}": {
      "delete": {
        "tags": [
          "Project Reports"
        ],
        "summary": "Delete a report",
        "operationId": "deleteReport",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Delete a specific project report generated with the GitHub app. These endpoints will be merged into the full-scans endpoint so\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:write"
      }
    },
    "/report/list": {
      "get": {
        "tags": [
          "Project Reports"
        ],
        "summary": "Get list of reports",
        "operationId": "getReportList",
        "security": [
          {
            "basicAuth": [
              "report:list"
            ]
          }
        ],
        "description": "Get all your project reports generated with the GitHub app. This endpoint will be merged into the full-scans endpoint soon.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:list"
      }
    },
    "/report/upload": {
      "put": {
        "tags": [
          "Project Reports"
        ],
        "summary": "Create a report",
        "operationId": "createReport",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Upload a lockfile to get your project analyzed by Socket.\nYou can upload multiple lockfiles in the same request, but each filename must be unique.\n\nThe name of the file must be in the supported list.\n\nFor example, these are valid filenames: `package.json`, `folder/package.json` and `deep/nested/folder/package.json`.\n\nThis endpoint consumes 100 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:write"
      }
    },
    "/report/view/{id}": {
      "get": {
        "tags": [
          "Project Reports"
        ],
        "summary": "View a report",
        "operationId": "getReport",
        "security": [
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "Get all the issues, packages, and scores related to an specific project report.\n\nThis endpoint consumes 10 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- report:read"
      }
    },
    "/repo/list": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "summary": "List GitHub repositories",
        "deprecated": true,
        "operationId": "getRepoList",
        "security": [
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Get all GitHub repositories associated with a Socket org.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- repo:list"
      }
    },
    "/openapi": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Returns the OpenAPI definition",
        "operationId": "getOpenAPI",
        "security": [
          {}
        ],
        "description": "Retrieve the API specification in an Openapi JSON format.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:"
      }
    },
    "/quota": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Get quota",
        "operationId": "getQuota",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get your current API quota. You can use this endpoint to prevent doing requests that might spend all your quota.\n\nThis endpoint consumes 0 units of your quota.\n\nThis endpoint requires the following org token scopes:\n- Any"
      }
    },
    "/organizations": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "List organizations",
        "operationId": "getOrganizations",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get information on the current organizations associated with the API key.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- Any"
      }
    },
    "/settings": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Calculate settings",
        "operationId": "postSettings",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get current settings for the requested organizations and default settings to allow deferrals.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- Any"
      }
    },
    "/npm/{package}/{version}/issues": {
      "get": {
        "tags": [
          "npm"
        ],
        "summary": "Get issues by package",
        "deprecated": true,
        "operationId": "getIssuesByNPMPackage",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get all the issues related with a particular npm package version.\nThis endpoint returns the issue type, location, and additional details related to each issue in the `props` attribute.\n\nYou can [see here](https://socket.dev/npm/issue) the full list of issues.\n\nThis endpoint consumes 1 unit of your quota.\n\nThis endpoint requires the following org token scopes:\n- Any"
      }
    },
    "/npm/{package}/{version}/score": {
      "get": {
        "tags": [
          "npm"
        ],
        "summary": "Get score by package",
        "deprecated": true,
        "operationId": "getScoreByNPMPackage",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get all the scores and metrics by category that are used to evaluate the package version.\n\nThis endpoint is deprecated. Use the batched \"Get Packages\" endpoint instead.\n\n- depscore: The average of all score factors. (0-1)\n- supplyChainRisk: Score factors relating to supply chain security (0-1)\n- downloadCount: The number of downloads for the package. Higher downloads contribute to a higher score.\n- supplyChainRiskIssueLow/Mid/High/Critical: The number of supply c[...]"
      }
    }
  }
}