{
  "openapi": "3.0.0",
  "info": {
    "description": "Specification of the Socket API endpoints",
    "title": "API Endpoints",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "https://api.socket.dev/v0"
    }
  ],
  "components": {
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "paths": {
    "/npm/{package}/{version}/issues": {
      "get": {
        "tags": [
          "NPM"
        ],
        "summary": "Get issues by package",
        "operationId": "getIssuesByNPMPackage",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get all the issues related with a particular npm package version.\nThis endpoint returns the issue type, location, and additional details related to each issue in the `props` attribute.\n\nYou can [see here](https://socket.dev/npm/issue) the full list of issues.\n\nThis endpoint consumes 1 unit of your quota."
      }
    },
    "/npm/{package}/{version}/score": {
      "get": {
        "tags": [
          "NPM"
        ],
        "summary": "Get score by package",
        "operationId": "getScoreByNPMPackage",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get all the scores and metrics by category that are used to evaluate the package version.\n\n- depscore: The average of all score factors. (0-1)\n- supplyChainRisk: Score factors relating to supply chain security (0-1)\n- downloadCount: The number of downloads for the package. Higher downloads contribute to a higher score.\n- supplyChainRiskIssueLow/Mid/High/Critical: The number of supply chain risk issues of varying severity. Lower numbers contribute to a higher score.\n[...]"
      }
    },
    "/report/delete/{id}": {
      "delete": {
        "tags": [
          "Project report"
        ],
        "summary": "Delete a report",
        "operationId": "deleteReport",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Delete a specific project report.\n\nThis endpoint consumes 10 units of your quota."
      }
    },
    "/report/list": {
      "get": {
        "tags": [
          "Project report"
        ],
        "summary": "Get list of reports",
        "operationId": "getReportList",
        "security": [
          {
            "basicAuth": [
              "report:list"
            ]
          }
        ],
        "description": "Get all your project reports.\n\nThis endpoint consumes 10 units of your quota."
      }
    },
    "/report/upload": {
      "put": {
        "tags": [
          "Project report"
        ],
        "summary": "Create a report",
        "operationId": "createReport",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Upload a lockfile to get your project analyzed by Socket.\nYou can upload multiple lockfiles in the same request, but each filename must be unique.\n\nThe name of the file must be in the supported list.\n\nFor example, these are valid filenames: `package.json`, `folder/package.json` and `deep/nested/folder/package.json`.\n\nThis endpoint consumes 100 units of your quota."
      }
    },
    "/report/view/{id}": {
      "get": {
        "tags": [
          "Project report"
        ],
        "summary": "View a report",
        "operationId": "getReport",
        "security": [
          {
            "basicAuth": [
              "report:read"
            ]
          }
        ],
        "description": "Get all the issues, packages, and scores related to an specific project report.\n\nThis endpoint consumes 10 units of your quota."
      }
    },
    "/report/supported": {
      "get": {
        "tags": [
          "Project report"
        ],
        "summary": "Get supported files for report",
        "operationId": "getReportSupportedFiles",
        "security": [
          {}
        ],
        "description": "Get a list of supported files for project report generation.\nFiles are categorized first by environment (e.g. NPM or PyPI), then by name.\n\nFiles whose names match the patterns returned by this endpoint can be uploaded for report generation.\nExamples of supported filenames include `package.json`, `package-lock.json`, and `yarn.lock`.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/openapi": {
      "get": {
        "tags": [
          "Openapi"
        ],
        "summary": "Returns the OpenAPI definition",
        "operationId": "getOpenAPI",
        "security": [
          {}
        ],
        "description": "Retrieve the API specification in an Openapi JSON format.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/quota": {
      "get": {
        "tags": [
          "Quota"
        ],
        "summary": "Get quota",
        "operationId": "getQuota",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get your current API quota. You can use this endpoint to prevent doing requests that might spend all your quota.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/organizations": {
      "get": {
        "tags": [
          "Organizations"
        ],
        "summary": "List organizations",
        "operationId": "getOrganizations",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get information on the current organizations associated with the API key.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/settings": {
      "post": {
        "tags": [
          "Settings"
        ],
        "summary": "Calculate settings",
        "operationId": "postSettings",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Get your current settings the requested organizations and default settings to allow deferrals.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/repo/list": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "summary": "Get list of repos and their latest project report",
        "operationId": "getRepoList",
        "security": [
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Get all repositories in an org including their latest project report.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/dependencies/search": {
      "post": {
        "tags": [
          "Dependencies"
        ],
        "summary": "Search dependencies",
        "operationId": "searchDependencies",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "description": "Search for any dependency that is being used in your organization.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/dependencies/upload": {
      "post": {
        "tags": [
          "Dependencies"
        ],
        "summary": "Create a snapshot of all dependencies from manifest information",
        "operationId": "createDependenciesSnapshot",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "Upload a set of manifest or lockfiles to get your dependency tree analyzed by Socket.\nYou can upload multiple lockfiles in the same request, but each filename must be unique.\n\nThe name of the file must be in the supported list.\n\nFor example, these are valid filenames: \"requirements.txt\", \"package.json\", \"folder/package.json\", and \"deep/nested/folder/package.json\".\n\nThis endpoint consumes 100 units of your quota."
      }
    },
    "/orgs/{org_slug}/repos": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "summary": "List repositories (unstable)",
        "operationId": "getOrgRepoList",
        "security": [
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Lists repositories for the specified organization.\n\nThis endpoint consumes 0 units of your quota."
      },
      "post": {
        "tags": [
          "Repositories"
        ],
        "summary": "Create repository (unstable)",
        "operationId": "createOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:create"
            ]
          }
        ],
        "description": "Create a repository.\n\nRepos collect Full scans and Diff scans and are typically associated with a git repo.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/orgs/{org_slug}/repos/{repo_slug}": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "summary": "Get repository (unstable)",
        "operationId": "getOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:list"
            ]
          }
        ],
        "description": "Retrieve a repository associated with an organization.\n\nThis endpoint consumes 0 units of your quota."
      },
      "post": {
        "tags": [
          "Repositories"
        ],
        "summary": "Update repository (unstable)",
        "operationId": "updateOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:update"
            ]
          }
        ],
        "description": "Update details of an existing repository.\n\nThis endpoint consumes 0 units of your quota."
      },
      "delete": {
        "tags": [
          "Repositories"
        ],
        "summary": "Delete repository (unstable)",
        "operationId": "deleteOrgRepo",
        "security": [
          {
            "basicAuth": [
              "repo:delete"
            ]
          }
        ],
        "description": "Delete a single repository and all of its associated Full scans and Diff scans.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/orgs/{org_slug}/full-scans": {
      "get": {
        "tags": [
          "Full scans"
        ],
        "summary": "List full scans (unstable)",
        "operationId": "getOrgFullScanList",
        "security": [
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Returns a paginated list of all full scans in an org, excluding SBOM artifacts.\n\nThis endpoint consumes 0 units of your quota."
      },
      "post": {
        "tags": [
          "Full scans"
        ],
        "summary": "Create full scan (unstable)",
        "operationId": "CreateOrgFullScan",
        "security": [
          {
            "basicAuth": [
              "full-scans:create"
            ]
          }
        ],
        "description": "Create a full scan from a set of package manifest files. Returns a full scan including all SBOM artifacts.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/orgs/{org_slug}/full-scans/{full_scan_id}": {
      "get": {
        "tags": [
          "Full scans"
        ],
        "summary": "Stream full scan (unstable)",
        "operationId": "getOrgFullScan",
        "security": [
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Stream all SBOM artifacts for a full scan.\n\nThis endpoint consumes 0 units of your quota."
      },
      "delete": {
        "tags": [
          "Full scans"
        ],
        "summary": "Delete full scan (unstable)",
        "operationId": "deleteOrgFullScan",
        "security": [
          {
            "basicAuth": [
              "full-scans:delete"
            ]
          }
        ],
        "description": "Delete an existing full scan.\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/orgs/{org_slug}/full-scans/{full_scan_id}/metadata": {
      "get": {
        "tags": [
          "Full scans"
        ],
        "summary": "Get full scan metadata (unstable)",
        "operationId": "getOrgFullScanMetadata",
        "security": [
          {
            "basicAuth": [
              "full-scans:list"
            ]
          }
        ],
        "description": "Get metadata for a single full scan\n\nThis endpoint consumes 0 units of your quota."
      }
    },
    "/analytics/org/{filter}": {
      "get": {
        "tags": [
          ""
        ],
        "summary": "Fetch the organization's analytics",
        "operationId": "getOrgAnalytics",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "This endpoint consumes 0 units of your quota."
      }
    },
    "/analytics/repo/{name}/{filter}": {
      "get": {
        "tags": [
          ""
        ],
        "summary": "Fetch repository analytics",
        "operationId": "getRepoAnalytics",
        "security": [
          {
            "basicAuth": [
              "report:write"
            ]
          }
        ],
        "description": "This endpoint consumes 0 units of your quota."
      }
    },
    "/purl": {
      "post": {
        "tags": [
          "Artifacts"
        ],
        "summary": "Get Packages (unstable)",
        "operationId": "batchArtifactFetch",
        "security": [
          {
            "basicAuth": [
              "artifacts:list"
            ]
          }
        ],
        "description": "Batch retrieval of package metadata and alerts by PURL strings\n\nThis endpoint consumes 100 units of your quota."
      }
    }
  }
}