/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/openapi': {
    /**
     * Returns the OpenAPI definition.
     *
     * Returns the OpenAPI 3.1 specification for the v1 API. No authentication
     * required.
     */
    get: {
      responses: {
        /**
         * Default Response.
         */
        200: {
          content: never
        }
      }
    }
  }
  '/v1/openapi.json': {
    /**
     * Returns the OpenAPI definition.
     *
     * Returns the OpenAPI 3.1 specification for the v1 API. No authentication
     * required.
     */
    get: {
      responses: {
        /**
         * Default Response.
         */
        200: {
          content: never
        }
      }
    }
  }
  '/v1/orgs/{org_slug}/events/': {
    /**
     * Post organization events.
     *
     * Send events directly to Socket.
     * Authentication: Organization API token only.
     * Required token scopes: *
     */
    post: {
      parameters: {
        path: {
          /**
           * Organization slug.
           */
          org_slug: string
        }
      }
      /**
       * Array of event payloads.
       */
      requestBody: {
        content: {
          'application/json': {
            action?: string
            alert_action?: string
            alert_count?: number
            api_error?: string
            artifact_purl?: string
            block_reason?: string
            block_source?: string
            blocked_alert_count?: number
            cached?: boolean
            client_action?: string
            client_ip?: string
            decision?: string
            event_category?: string
            event_id?: string
            event_kind?: string
            event_sender_created_at?: string
            event_type?: string
            ignore_reason?: string
            input_purl?: string
            machine_id?: string
            monitor_reason?: string
            parser_name?: string
            parser_version?: string
            private_registry_request_id?: string
            purlCheckLatencyMs?: number
            purl_check_latency_ms?: number
            registryFqdn?: string
            repo?: string
            request_id?: string
            response_code?: number
            socket_api_response_code?: number
            socket_client_version?: string
            source_path?: string
            stale?: boolean
            trace_id?: string
            upstream_host?: string
            upstream_path?: string
            upstream_status?: number
            user_agent?: string
            versions?: {
              [key: string]: string
            }
            warn_reason?: string
            [key: string]: unknown
          }[]
        }
      }
      responses: {
        /**
         * Events ingestion metadata.
         */
        200: {
          content: {
            'application/json': {
              [key: string]: unknown
            }
          }
        }
        /**
         * Events ingestion metadata.
         */
        201: {
          content: {
            'application/json': {
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        400: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        401: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        403: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        404: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        413: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        500: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
      }
    }
  }
  '/v1/orgs/{org_slug}/purl/versions/{purl}': {
    /**
     * List published versions for a package by PURL.
     *
     * Given a package URL (PURL) *without* a version, returns every version
     * Socket knows about for that package along with its publish date, sorted
     * newest-first by publish date.
     * This lets you enforce version policies such as "N-1" (allow the previous
     * release, block the newest) without querying a package registry directly.
     * Versions with no known publish date are listed last.
     * **Ordering includes prereleases.** Sorting is by publish date only, so
     * index 0 is the most recently *published* version, not necessarily the
     * newest stable release. On npm in particular the newest publishes are
     * often canaries or release candidates, so a consumer that reads index 1
     * as "N-1" can land on a prerelease. Each entry carries a `prerelease`
     * flag for this: filter out entries where `prerelease` is `true` before
     * applying an N-1 rule. `prerelease` is `null` when the ecosystem's
     * version grammar has no canonical prerelease parser, or when the version
     * string itself does not parse — treat null according to your own policy
     * rather than as an error.
     * Pass `limit` to cap how many entries come back; it is applied after
     * sorting, so `limit=2` is all the N-1 use case needs. A `limit` that
     * is not a positive integer is rejected with a 400 rather than clamped.
     * The PURL must be percent-encoded as a single path segment
     * (`encodeURIComponent`); an unencoded `/` will not match this route.
     * Any version on the PURL is ignored — the full history always comes back.
     * The HuggingFace `type` qualifier (model, dataset, or space) is honored.
     * A well-formed PURL for an ecosystem that does not support version
     * listing returns a 400 rather than a server error.
     * Authentication: Organization API token, OAuth2, or NextAuth session.
     * Required token scope: `packages:list`. Costs 100 quota units.
     */
    get: {
      parameters: {
        query?: {
          /**
           * Maximum number of version entries to return, applied after sorting.
           * Omit for the full history.
           */
          limit?: number
        }
        path: {
          /**
           * Organization slug.
           */
          org_slug: string
          /**
           * Package URL, percent-encoded as a single path segment. Example:
           * pkg%3Anpm%2F%40babel%2Fcore.
           */
          purl: string
        }
      }
      responses: {
        /**
         * Default Response.
         */
        200: {
          content: {
            'application/json': {
              /**
               * The PURL as received, echoed back.
               */
              purl: string
              /**
               * Known versions, newest-first by publish date. Ordering includes
               * prereleases, so index 0 is the most recent publish rather than
               * the newest stable release.
               */
              versions: {
                /**
                 * The version string as the ecosystem reports it.
                 */
                version: string
                /**
                 * ISO-8601 publish date, or null when the ecosystem reports
                 * none. Undated versions are listed last.
                 */
                publishedAt: null | string
                /**
                 * True when this version is a prerelease (canary, release
                 * candidate, dev, beta) according to the ecosystem's own
                 * version grammar. Null means unknown — either the ecosystem
                 * has no canonical prerelease parser, or this version string
                 * does not parse. Null is not an error.
                 */
                prerelease: null | boolean
              }[]
            }
          }
        }
        /**
         * Default Response.
         */
        400: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        401: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        403: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        404: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        429: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
      }
    }
  }
  '/v1/orgs/{org_slug}/threat-campaigns/': {
    /**
     * List threat campaigns.
     *
     * Returns a paginated list of supply chain attack campaigns. Supports
     * filtering by status, ecosystem, and an incremental sync parameter
     * (`updated_after`). Package PURLs are not inlined on the campaign object —
     * they are their own paginated resource. Fetch them per campaign from
     * `/threat-campaigns/:campaign_id/packages`. Authentication: Organization
     * API token, OAuth2, or NextAuth session. Required token scope:
     * `threat-campaigns:list`. This endpoint requires an Enterprise Plan with
     * the Threat Feed add-on.
     */
    get: {
      parameters: {
        query?: {
          /**
           * Filter by campaign status. Defaults to ongoing.
           */
          status?: 'ongoing' | 'past'
          /**
           * Filter by ecosystem (e.g. npm, pypi, maven).
           */
          ecosystem?: string
          /**
           * Unix timestamp in seconds. Only return campaigns updated after this
           * time. Omit to return all matching campaigns.
           */
          updated_after?: string
          /**
           * Number of campaigns per page. Default 30, max 100.
           */
          per_page?: number
          /**
           * Opaque cursor for pagination. Use the endCursor value from the
           * previous response.
           */
          cursor?: string
        }
        path: {
          /**
           * Organization slug.
           */
          org_slug: string
        }
      }
      responses: {
        /**
         * Default Response.
         */
        200: {
          content: {
            'application/json': {
              items: {
                id: string
                name: string
                description: string
                /**
                 * @enum {string}
                 */
                status: 'ongoing' | 'past'
                ecosystem: null | string[]
                firstDiscovered: null | string
                lastActivity: null | string
                blogUrls: string[]
                /**
                 * Number of threat feed entries linked to this campaign.
                 */
                linkedThreatCount: number
                /**
                 * Number of distinct package artifacts linked to this
                 * campaign.
                 */
                linkedPackageArtifactsCount: number
                /**
                 * URL of the public campaign page on socket.dev, or null if
                 * the campaign has no public page.
                 */
                htmlUrl: null | string
                /**
                 * Format: date-time.
                 */
                createdAt: string
                /**
                 * Format: date-time.
                 */
                updatedAt: string
                [key: string]: unknown
              }[]
              endCursor?: null | string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        400: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        401: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        403: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        404: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        429: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
      }
    }
  }
  '/v1/orgs/{org_slug}/threat-campaigns/{campaign_id}/': {
    /**
     * Get a threat campaign.
     *
     * Returns a single supply chain attack campaign by ID. Same shape as one
     * item from the campaigns list; package PURLs are not inlined — fetch them
     * from the paginated `/threat-campaigns/:campaign_id/packages` resource
     * instead. Useful for filling in cached campaign metadata client-side when
     * crawling the campaigns list or packages feed. Authentication:
     * Organization API token, OAuth2, or NextAuth session. Required token
     * scope: `threat-campaigns:list`. This endpoint requires an Enterprise Plan
     * with the Threat Feed add-on.
     */
    get: {
      parameters: {
        path: {
          /**
           * Organization slug.
           */
          org_slug: string
          /**
           * Campaign ID.
           */
          campaign_id: string
        }
      }
      responses: {
        /**
         * Default Response.
         */
        200: {
          content: {
            'application/json': {
              id: string
              name: string
              description: string
              /**
               * @enum {string}
               */
              status: 'ongoing' | 'past'
              ecosystem: null | string[]
              firstDiscovered: null | string
              lastActivity: null | string
              blogUrls: string[]
              /**
               * Number of threat feed entries linked to this campaign.
               */
              linkedThreatCount: number
              /**
               * Number of distinct package artifacts linked to this campaign.
               */
              linkedPackageArtifactsCount: number
              /**
               * URL of the public campaign page on socket.dev, or null if the
               * campaign has no public page.
               */
              htmlUrl: null | string
              /**
               * Format: date-time.
               */
              createdAt: string
              /**
               * Format: date-time.
               */
              updatedAt: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        400: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        401: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        403: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        404: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        429: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
      }
    }
  }
  '/v1/orgs/{org_slug}/threat-campaigns/{campaign_id}/packages': {
    /**
     * List packages for a threat campaign.
     *
     * Returns a cursor-paginated list of package PURLs affected by a single
     * supply chain attack campaign. This is the primary way to retrieve all
     * packages for a known campaign without an inline, unbounded list on the
     * campaign object. Pagination follows the same `{ items, endCursor }`
     * envelope as the campaigns list. Pass the `endCursor` value back as
     * `cursor` to fetch the next page. Authentication: Organization API token,
     * OAuth2, or NextAuth session. Required token scope:
     * `threat-campaigns:list`. This endpoint requires an Enterprise Plan with
     * the Threat Feed add-on.
     */
    get: {
      parameters: {
        query?: {
          /**
           * Number of packages per page. Default 100, max 1000.
           */
          per_page?: number
          /**
           * Opaque cursor for pagination. Use the endCursor value from the
           * previous response.
           */
          cursor?: string
        }
        path: {
          /**
           * Organization slug.
           */
          org_slug: string
          /**
           * Campaign ID.
           */
          campaign_id: string
        }
      }
      responses: {
        /**
         * Default Response.
         */
        200: {
          content: {
            'application/json': {
              /**
               * Package PURLs associated with this campaign.
               */
              items: string[]
              endCursor?: null | string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        400: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        401: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        403: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        404: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
        /**
         * Default Response.
         */
        429: {
          content: {
            'application/json': {
              statusCode: number
              error: string
              message: string
              [key: string]: unknown
            }
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {}
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export type operations = Record<string, never>
