/**
 * @file Fleet oxlint plugin. Custom rules that encode the fleet's CLAUDE.md
 *   style guide as lint errors with autofix where the rewrite is unambiguous.
 *   Why a plugin instead of a separate scanner: oxlint's native plugin surface
 *   integrates with the existing `pnpm run lint` pipeline, inherits oxlint's
 *   AST + sourcemap + fix-application machinery, and keeps the rule set
 *   discoverable via `oxlint --rules`. Wiring: `.config/fleet/oxlintrc.json`
 *   adds this plugin via `jsPlugins: ["../oxlint-plugin/index.mts"]` and
 *   enables rules under the `socket/` namespace. Each rule is its own dir under
 *   `fleet/` (mirrors `.claude/hooks/fleet/<name>/`); this file's rule imports
 *   + `rules: {}` registry are generated by `pnpm run sync-oxlint-rules` from
 *   that dir inventory.
 */

import exportTopLevelFunctions from './fleet/export-top-level-functions/index.mts'
import inclusiveLanguage from './fleet/inclusive-language/index.mts'
import maxFileLines from './fleet/max-file-lines/index.mts'
import noBareCryptoNamedUsage from './fleet/no-bare-crypto-named-usage/index.mts'
import noBareSpawnChildprocAccess from './fleet/no-bare-spawn-childproc-access/index.mts'
import noBooleanTrapParam from './fleet/no-boolean-trap-param/index.mts'
import noCachedForOnIterable from './fleet/no-cached-for-on-iterable/index.mts'
import noConsolePreferLogger from './fleet/no-console-prefer-logger/index.mts'
import noDefaultExport from './fleet/no-default-export/index.mts'
import noDynamicImportOutsideBundle from './fleet/no-dynamic-import-outside-bundle/index.mts'
import noEs2023ArrayMethodsBelowNode20 from './fleet/no-es2023-array-methods-below-node20/index.mts'
import noEslintBiomeConfigRef from './fleet/no-eslint-biome-config-ref/index.mts'
import noFetchPreferHttpRequest from './fleet/no-fetch-prefer-http-request/index.mts'
import noFileScopeOxlintDisable from './fleet/no-file-scope-oxlint-disable/index.mts'
import noInlineDeferAsync from './fleet/no-inline-defer-async/index.mts'
import noInlineLogger from './fleet/no-inline-logger/index.mts'
import noLoggerNewlineLiteral from './fleet/no-logger-newline-literal/index.mts'
import noNpxDlx from './fleet/no-npx-dlx/index.mts'
import noPackageManagerAutoUpdateReenable from './fleet/no-package-manager-auto-update-reenable/index.mts'
import noPlaceholders from './fleet/no-placeholders/index.mts'
import noPlatformSpecificImport from './fleet/no-platform-specific-import/index.mts'
import noProcessChdir from './fleet/no-process-chdir/index.mts'
import noProcessCwdInScriptsHooks from './fleet/no-process-cwd-in-scripts-hooks/index.mts'
import noPromiseRace from './fleet/no-promise-race/index.mts'
import noPromiseRaceInLoop from './fleet/no-promise-race-in-loop/index.mts'
import noSrcImportInTestExpect from './fleet/no-src-import-in-test-expect/index.mts'
import noStatusEmoji from './fleet/no-status-emoji/index.mts'
import noStructuredClonePreferJson from './fleet/no-structured-clone-prefer-json/index.mts'
import noSyncRmInTestLifecycle from './fleet/no-sync-rm-in-test-lifecycle/index.mts'
import noTopLevelAwait from './fleet/no-top-level-await/index.mts'
import noUnderscoreIdentifier from './fleet/no-underscore-identifier/index.mts'
import noUseStrictInEsm from './fleet/no-use-strict-in-esm/index.mts'
import noVitestEmptyTest from './fleet/no-vitest-empty-test/index.mts'
import noVitestFocusedTests from './fleet/no-vitest-focused-tests/index.mts'
import noVitestIdenticalTitle from './fleet/no-vitest-identical-title/index.mts'
import noVitestSkippedTests from './fleet/no-vitest-skipped-tests/index.mts'
import noVitestStandaloneExpect from './fleet/no-vitest-standalone-expect/index.mts'
import noWhichForLocalBin from './fleet/no-which-for-local-bin/index.mts'
import optionalExplicitUndefined from './fleet/optional-explicit-undefined/index.mts'
import optionsNullProto from './fleet/options-null-proto/index.mts'
import personalPathPlaceholders from './fleet/personal-path-placeholders/index.mts'
import preferAsyncSpawn from './fleet/prefer-async-spawn/index.mts'
import preferCachedForLoop from './fleet/prefer-cached-for-loop/index.mts'
import preferEllipsisChar from './fleet/prefer-ellipsis-char/index.mts'
import preferEnvAsBoolean from './fleet/prefer-env-as-boolean/index.mts'
import preferErrorMessage from './fleet/prefer-error-message/index.mts'
import preferExistsSync from './fleet/prefer-exists-sync/index.mts'
import preferFindRepoRoot from './fleet/prefer-find-repo-root/index.mts'
import preferFindUpPackageJson from './fleet/prefer-find-up-package-json/index.mts'
import preferFunctionDeclaration from './fleet/prefer-function-declaration/index.mts'
import preferMockImport from './fleet/prefer-mock-import/index.mts'
import preferNodeBuiltinImports from './fleet/prefer-node-builtin-imports/index.mts'
import preferNodeModulesDotCache from './fleet/prefer-node-modules-dot-cache/index.mts'
import preferNonCapturingGroup from './fleet/prefer-non-capturing-group/index.mts'
import preferOptionalChain from './fleet/prefer-optional-chain/index.mts'
import preferPureCallForm from './fleet/prefer-pure-call-form/index.mts'
import preferSafeDelete from './fleet/prefer-safe-delete/index.mts'
import preferSeparateTypeImport from './fleet/prefer-separate-type-import/index.mts'
import preferShellWin32 from './fleet/prefer-shell-win32/index.mts'
import preferSpawnOverExecsync from './fleet/prefer-spawn-over-execsync/index.mts'
import preferStableExternalSemver from './fleet/prefer-stable-external-semver/index.mts'
import preferStableSelfImport from './fleet/prefer-stable-self-import/index.mts'
import preferStaticTypeImport from './fleet/prefer-static-type-import/index.mts'
import preferTypeboxSchema from './fleet/prefer-typebox-schema/index.mts'
import preferUndefinedOverNull from './fleet/prefer-undefined-over-null/index.mts'
import preferWindowsTestHelpers from './fleet/prefer-windows-test-helpers/index.mts'
import requireAsyncIifeEntry from './fleet/require-async-iife-entry/index.mts'
import requireRegexComment from './fleet/require-regex-comment/index.mts'
import requireVitestGlobalsImport from './fleet/require-vitest-globals-import/index.mts'
import socketApiTokenEnv from './fleet/socket-api-token-env/index.mts'
import sortArrayLiterals from './fleet/sort-array-literals/index.mts'
import sortBooleanChains from './fleet/sort-boolean-chains/index.mts'
import sortEqualityDisjunctions from './fleet/sort-equality-disjunctions/index.mts'
import sortNamedImports from './fleet/sort-named-imports/index.mts'
import sortObjectLiteralProperties from './fleet/sort-object-literal-properties/index.mts'
import sortRegexAlternations from './fleet/sort-regex-alternations/index.mts'
import sortSetArgs from './fleet/sort-set-args/index.mts'
import sortSourceMethods from './fleet/sort-source-methods/index.mts'
import useFleetCanonicalApiTokenGetter from './fleet/use-fleet-canonical-api-token-getter/index.mts'

/**
 * @type {import('eslint').ESLint.Plugin}
 */
const plugin = {
  meta: {
    name: 'socket',
    version: '0.5.0',
  },
  rules: {
    'export-top-level-functions': exportTopLevelFunctions,
    'inclusive-language': inclusiveLanguage,
    'max-file-lines': maxFileLines,
    'no-bare-crypto-named-usage': noBareCryptoNamedUsage,
    'no-bare-spawn-childproc-access': noBareSpawnChildprocAccess,
    'no-boolean-trap-param': noBooleanTrapParam,
    'no-cached-for-on-iterable': noCachedForOnIterable,
    'no-console-prefer-logger': noConsolePreferLogger,
    'no-default-export': noDefaultExport,
    'no-dynamic-import-outside-bundle': noDynamicImportOutsideBundle,
    'no-es2023-array-methods-below-node20': noEs2023ArrayMethodsBelowNode20,
    'no-eslint-biome-config-ref': noEslintBiomeConfigRef,
    'no-fetch-prefer-http-request': noFetchPreferHttpRequest,
    'no-file-scope-oxlint-disable': noFileScopeOxlintDisable,
    'no-inline-defer-async': noInlineDeferAsync,
    'no-inline-logger': noInlineLogger,
    'no-logger-newline-literal': noLoggerNewlineLiteral,
    'no-npx-dlx': noNpxDlx,
    'no-package-manager-auto-update-reenable':
      noPackageManagerAutoUpdateReenable,
    'no-placeholders': noPlaceholders,
    'no-platform-specific-import': noPlatformSpecificImport,
    'no-process-chdir': noProcessChdir,
    'no-process-cwd-in-scripts-hooks': noProcessCwdInScriptsHooks,
    'no-promise-race': noPromiseRace,
    'no-promise-race-in-loop': noPromiseRaceInLoop,
    'no-src-import-in-test-expect': noSrcImportInTestExpect,
    'no-status-emoji': noStatusEmoji,
    'no-structured-clone-prefer-json': noStructuredClonePreferJson,
    'no-sync-rm-in-test-lifecycle': noSyncRmInTestLifecycle,
    'no-top-level-await': noTopLevelAwait,
    'no-underscore-identifier': noUnderscoreIdentifier,
    'no-use-strict-in-esm': noUseStrictInEsm,
    'no-vitest-empty-test': noVitestEmptyTest,
    'no-vitest-focused-tests': noVitestFocusedTests,
    'no-vitest-identical-title': noVitestIdenticalTitle,
    'no-vitest-skipped-tests': noVitestSkippedTests,
    'no-vitest-standalone-expect': noVitestStandaloneExpect,
    'no-which-for-local-bin': noWhichForLocalBin,
    'optional-explicit-undefined': optionalExplicitUndefined,
    'options-null-proto': optionsNullProto,
    'personal-path-placeholders': personalPathPlaceholders,
    'prefer-async-spawn': preferAsyncSpawn,
    'prefer-cached-for-loop': preferCachedForLoop,
    'prefer-ellipsis-char': preferEllipsisChar,
    'prefer-env-as-boolean': preferEnvAsBoolean,
    'prefer-error-message': preferErrorMessage,
    'prefer-exists-sync': preferExistsSync,
    'prefer-find-repo-root': preferFindRepoRoot,
    'prefer-find-up-package-json': preferFindUpPackageJson,
    'prefer-function-declaration': preferFunctionDeclaration,
    'prefer-mock-import': preferMockImport,
    'prefer-node-builtin-imports': preferNodeBuiltinImports,
    'prefer-node-modules-dot-cache': preferNodeModulesDotCache,
    'prefer-non-capturing-group': preferNonCapturingGroup,
    'prefer-optional-chain': preferOptionalChain,
    'prefer-pure-call-form': preferPureCallForm,
    'prefer-safe-delete': preferSafeDelete,
    'prefer-separate-type-import': preferSeparateTypeImport,
    'prefer-shell-win32': preferShellWin32,
    'prefer-spawn-over-execsync': preferSpawnOverExecsync,
    'prefer-stable-external-semver': preferStableExternalSemver,
    'prefer-stable-self-import': preferStableSelfImport,
    'prefer-static-type-import': preferStaticTypeImport,
    'prefer-typebox-schema': preferTypeboxSchema,
    'prefer-undefined-over-null': preferUndefinedOverNull,
    'prefer-windows-test-helpers': preferWindowsTestHelpers,
    'require-async-iife-entry': requireAsyncIifeEntry,
    'require-regex-comment': requireRegexComment,
    'require-vitest-globals-import': requireVitestGlobalsImport,
    'socket-api-token-env': socketApiTokenEnv,
    'sort-array-literals': sortArrayLiterals,
    'sort-boolean-chains': sortBooleanChains,
    'sort-equality-disjunctions': sortEqualityDisjunctions,
    'sort-named-imports': sortNamedImports,
    'sort-object-literal-properties': sortObjectLiteralProperties,
    'sort-regex-alternations': sortRegexAlternations,
    'sort-set-args': sortSetArgs,
    'sort-source-methods': sortSourceMethods,
    'use-fleet-canonical-api-token-getter': useFleetCanonicalApiTokenGetter,
  },
}

export default plugin
