import { describe, expect, it, vi } from 'vitest'
import {
  extractMethods,
  renderApiDocs,
  renderMethod,
} from '../../../scripts/repo/gen-api-docs-lib.mts'

const source = vi.hoisted(() => ({ text: '' }))
vi.mock(import('node:fs'), async importOriginal => {
  const original = await importOriginal()
  return {
    ...original,
    readFileSync: vi.fn((file, ...args) => {
      if (String(file).endsWith('socket-sdk-class.mts')) {
        return source.text
      }
      if (String(file).endsWith('api-method-quota-and-permissions.json')) {
        return JSON.stringify({
          api: { GetScan: { quota: 3, permissions: ['scan:read'] } },
        })
      }
      return Reflect.apply(original.readFileSync, original, [file, ...args])
    }),
  }
})

describe('API documentation method extraction', () => {
  it('retains nested signatures, generator metadata, case-insensitive quotas, and overload deduplication', () => {
    source.text = `class SocketSdk {
  /**
   * Read a scan.
   * @operationId getscan
   */
  async *readScan(options: { nested: { enabled: boolean } }): AsyncGenerator<string> {
    yield 'scan'
  }
  async *readScan(): AsyncGenerator<string> {
    yield 'overload'
  }
}`
    expect(extractMethods()).toEqual([
      {
        isGenerator: true,
        name: 'readScan',
        operationId: 'getscan',
        permissions: ['scan:read'],
        quota: 3,
        signature:
          'async *readScan(options: { nested: { enabled: boolean } }): AsyncGenerator<string>',
        summary: 'Read a scan.',
      },
    ])
  })
})

describe('API documentation reference rendering', () => {
  const method = {
    name: 'readScan',
    isGenerator: false,
    signature: 'readScan(): Promise<Scan>',
    summary: 'Read a scan.',
    operationId: 'getScan',
    quota: 3,
    permissions: ['scan:read'],
  }

  it('keeps short signatures visible', () => {
    const rendered = renderMethod(method)
    expect(rendered).toContain('```typescript\nreadScan(): Promise<Scan>\n```')
    expect(rendered).not.toContain('<details>')
    expect(rendered).toContain('**Permissions:** `scan:read`')
  })

  it('folds long signatures while retaining the summary and permission metadata', () => {
    const parameters = [...Array(20).keys()].map(
      index => `  option${index}?: boolean,`,
    )
    const signature = `readScan(\n${parameters.join('\n')}\n): Promise<Scan>`
    const rendered = renderMethod({ ...method, signature })
    expect(rendered).toContain('Read a scan.\n\n<details>')
    expect(rendered).toContain('<summary>Signature</summary>')
    expect(rendered).toContain(
      `\n\n\`\`\`typescript\n${signature}\n\`\`\`\n\n</details>`,
    )
    expect(rendered).toContain('</details>\n\n**Quota:**')
    expect(rendered).toContain('**Permissions:** `scan:read`')
  })

  it('marks generated documentation with plain punctuation', () => {
    expect(renderApiDocs([method])).toContain(
      'AUTOGENERATED. Do not edit by hand.',
    )
  })
})
