#!/usr/bin/env node
// Claude Code PreToolUse hook — no-github-ai-attribution-guard.
//
// Blocks AI-attribution boilerplate ("This PR was generated by Claude",
// "Assisted-by: Claude Code:opus-4-8", "Co-Authored-By: Claude",
// "🤖 Generated with Claude", a `claude.ai/code/session_` URL, …) from being
// posted to a PUBLIC human-facing prose surface. Two families of surface:
//
//   • GitHub via `gh` — PR body + title, PR/issue/commit comments, PR reviews
//     (approvals + rejections), issue body + title, release notes, discussions
//     (via the API), and gists. Detection is AST-based (the fleet
//     `shell-command` parser), so it sees through quoting, `&&`/`|`/`;` chains,
//     and `$(…)`.
//   • External trackers/chat via MCP — Linear (issue / comment / status-update /
//     document / project bodies), Slack messages, and any other `mcp__*` tool
//     whose input carries prose. Every string field of the tool input is
//     scanned.
//
// Commit MESSAGES are out of scope here — the commit-msg git hook strips
// attribution from them and pre-push blocks it; this guard covers the prose
// surfaces those hooks never see. The detector is the SAME
// `containsAiAttribution` both use, imported from the gate-free shared module
// so the guard and the git hooks never diverge on what counts as attribution.
//
// Fix: remove the attribution footer/line from the prose value and re-run.
//      A human-facing summary / comment / message doesn't need an AI byline
//      (CLAUDE.md → no AI attribution).
//
// Bypass: `Allow ai-attribution bypass`.

import type { ToolCallPayload } from '../_shared/payload.mts'

import { containsAiAttribution } from '../../../../.git-hooks/_shared/ai-attribution.mts'
import { block, defineHook, runHook } from '../_shared/guard.mts'
import { readCommand } from '../_shared/payload.mts'
import { commandsFor } from '../_shared/shell-command.mts'
import {
  BYPASS_LOOKBACK_USER_TURNS,
  bypassPhrasePresent,
} from '../_shared/transcript.mts'

const BYPASS_PHRASE = 'Allow ai-attribution bypass'

// Dispatcher pre-flight: a `gh` invocation carries the substring `gh`; every
// MCP tool call carries `mcp__` in its tool_name. A payload with neither can't
// match, so the dispatcher skips this guard.
export const triggers: readonly string[] = ['gh', 'mcp__']

// `gh` subcommands (first non-flag arg) that post prose to a public surface.
const PROSE_SUBCOMMANDS: ReadonlySet<string> = new Set([
  'api', // commit comments + GraphQL discussions carry a body= field
  'discussion',
  'gist',
  'issue',
  'pr',
  'release',
])

// Flags whose value is human-facing prose (a body, title, or release notes).
const PROSE_FLAGS: ReadonlySet<string> = new Set([
  '--body',
  '--body-text',
  '--notes',
  '--title',
  '-b',
  '-t',
])

// `gh api` field flags — the value is a `body=…` / `title=…` kv string.
const API_FIELD_FLAGS: ReadonlySet<string> = new Set([
  '--field',
  '--raw-field',
  '-F',
  '-f',
])

/**
 * Pull every prose token a `gh` command would post: body / title / notes flag
 * values and `gh api` `body=` / `title=` fields, from the AST-parsed args
 * (already unquoted, chain- and `$(…)`-aware). `--body-file` / `--notes-file`
 * (file paths) are out of scope — we only inspect args-as-text.
 */
export function extractProse(command: string): string {
  const out: string[] = []
  for (const cmd of commandsFor(command, 'gh')) {
    const { args } = cmd
    const isProse = args.some(
      a => !a.startsWith('-') && PROSE_SUBCOMMANDS.has(a),
    )
    if (!isProse) {
      continue
    }
    for (let i = 0, { length } = args; i < length; i += 1) {
      const arg = args[i]!
      if (PROSE_FLAGS.has(arg)) {
        const value = args[i + 1]
        if (value !== undefined) {
          out.push(value)
        }
        continue
      }
      const eq = arg.indexOf('=')
      if (eq > 0 && PROSE_FLAGS.has(arg.slice(0, eq))) {
        out.push(arg.slice(eq + 1))
        continue
      }
      if (API_FIELD_FLAGS.has(arg)) {
        const value = args[i + 1]
        if (
          value !== undefined &&
          (value.startsWith('body=') || value.startsWith('title='))
        ) {
          out.push(value.slice(value.indexOf('=') + 1))
        }
      }
    }
  }
  return out.join('\n')
}

/**
 * Pull every string field an MCP tool call carries (Linear issue/comment/
 * status/document/project bodies, Slack message text, etc.). The tool-input
 * shape varies per MCP server, so scan all string values rather than pinning
 * field names — a body under any key is still a human-facing prose surface.
 */
export function extractMcpProse(payload: ToolCallPayload): string {
  const input = payload.tool_input
  if (input === undefined || input === null || typeof input !== 'object') {
    return ''
  }
  const out: string[] = []
  for (const value of Object.values(input as Record<string, unknown>)) {
    if (typeof value === 'string') {
      out.push(value)
    }
  }
  return out.join('\n')
}

export const check = (
  payload: ToolCallPayload,
): ReturnType<typeof block> | undefined => {
  const toolName = payload?.tool_name
  let prose = ''
  let surface = ''
  if (toolName === 'Bash') {
    const command = readCommand(payload)
    if (command) {
      prose = extractProse(command)
      surface =
        'a public GitHub prose surface (PR/issue body or title, ' +
        'PR/issue/commit comment, review, release notes, discussion, or gist)'
    }
  } else if (typeof toolName === 'string' && toolName.startsWith('mcp__')) {
    prose = extractMcpProse(payload)
    surface =
      'an external prose surface (Linear issue/comment/status/document, ' +
      'Slack message, or similar)'
  }

  if (!prose || !containsAiAttribution(prose)) {
    return undefined
  }

  if (
    bypassPhrasePresent(
      payload.transcript_path,
      BYPASS_PHRASE,
      BYPASS_LOOKBACK_USER_TURNS,
    )
  ) {
    return undefined
  }

  return block(
    [
      '🚨 no-github-ai-attribution-guard: blocked a command posting',
      `   AI-attribution boilerplate to ${surface}.`,
      '',
      'A human-facing summary / comment / message must not carry an AI byline',
      '("This PR was generated by Claude", "Assisted-by: …",',
      '"Co-Authored-By: Claude", "🤖 Generated with …", a',
      'claude.ai/code/session_ URL, etc.) — CLAUDE.md → no AI attribution.',
      '',
      'Fix: remove the attribution footer/line from the prose value and re-run.',
      '',
      `Bypass (the user must type verbatim in a recent turn): \`${BYPASS_PHRASE}\``,
    ].join('\n'),
  )
}

export const hook = defineHook({
  bypass: ['ai-attribution'],
  bypassMode: 'manual',
  bypassOptional: true,
  check,
  event: 'PreToolUse',
  matcher: ['Bash', 'mcp__.*'],
  triggers,
  type: 'guard',
})
void runHook(hook, import.meta.url)
