// Generated by scripts/repo/gen/bootstrap.mts from scripts/fleet/pnpm/ecosystems.mts.
// The install fingerprint and Actions cache resolve before npm dependencies exist.
// oxlint-disable-next-line socket/prefer-spawn-over-execsync -- dep-0 config query
import { execFileSync as pnpmExecFileSync } from 'node:child_process'
import pnpmCrypto from 'node:crypto'
import {
  closeSync as pnpmCloseSync,
  constants as pnpmConstants,
  fstatSync as pnpmFstatSync,
  lstatSync as pnpmLstatSync,
  opendirSync as pnpmOpendirSync,
  openSync as pnpmOpenSync,
  readSync as pnpmReadSync,
  realpathSync as pnpmRealpathSync,
} from 'node:fs'

import pnpmPath from 'node:path'
import pnpmProcess from 'node:process'

const PNPM_CONFIG_TIMEOUT_MS = 5000
const PNPM_CONFIG_MAX_BYTES = 1_048_576
const PNPM_INPUT_MAX_ENTRIES = 50_000
const PNPM_INPUT_MAX_BYTES = 16 * 1024 * 1024
const PNPM_INPUT_SKIP_DIRS = new Set([
  '.cache',
  '.git',
  '.pnpm',
  '.venv',
  'build',
  'coverage',
  'deps',
  'external',
  'fixtures',
  'node_modules',
  'target',
  'third_party',
  'upstream',
  'vendor',
])

function pnpmConfigRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

export function pnpmEcosystemOwnership(config) {
  if (!pnpmConfigRecord(config)) {
    throw new TypeError(
      'Invalid pnpm configuration. Where: ecosystem ownership. Saw a non-object; wanted parsed pnpm config. Fix the workspace configuration.',
    )
  }
  const ownership = { cargo: false, python: false }
  for (const name of ['cargo', 'python']) {
    const section = config[name]
    if (section === undefined || section === null) {
      continue
    }
    if (
      !pnpmConfigRecord(section) ||
      (section['enabled'] !== undefined &&
        typeof section['enabled'] !== 'boolean')
    ) {
      throw new TypeError(
        `Invalid pnpm ${name} setting. Where: ecosystem ownership. Wanted an enabled boolean. Fix pnpm-workspace.yaml.`,
      )
    }
    ownership[name] = section['enabled'] === true
  }
  return ownership
}

export function readPnpmEcosystemOwnership(root, options = {}) {
  if (options.config !== undefined) {
    return pnpmEcosystemOwnership(options.config)
  }
  const args = ['config', 'list', '--json']
  const windows = pnpmProcess.platform === 'win32'
  let config
  try {
    config = JSON.parse(
      pnpmExecFileSync(
        windows ? 'bash' : 'pnpm',
        windows ? ['-c', 'exec pnpm "$@"', 'pnpm', ...args] : args,
        {
          cwd: root,
          encoding: 'utf8',
          maxBuffer: PNPM_CONFIG_MAX_BYTES,
          stdio: ['ignore', 'pipe', 'pipe'],
          timeout: PNPM_CONFIG_TIMEOUT_MS,
        },
      ),
    )
  } catch {
    throw new Error(
      'Cannot read pnpm ecosystem ownership. Where: pnpm config list --json. Wanted valid configuration within five seconds. Fix pnpm setup or workspace configuration and retry.',
    )
  }
  return pnpmEcosystemOwnership(config)
}

function isPnpmInputDirectory(name) {
  return (
    !PNPM_INPUT_SKIP_DIRS.has(name) &&
    !name.endsWith('-bundled') &&
    !name.endsWith('-vendored')
  )
}

function capturePnpmDirectory(directory) {
  const metadata = pnpmLstatSync(directory)
  if (!metadata.isDirectory() || pnpmRealpathSync(directory) !== directory) {
    throw new Error(
      `Pnpm input directory changed. Where: ${directory}. Wanted a contained directory without symlinks. Retry after edits finish.`,
    )
  }
  return {
    __proto__: null,
    dev: metadata.dev,
    ino: metadata.ino,
  }
}

function assertPnpmDirectories(directory, scan) {
  let current = directory
  while (true) {
    const expected = scan.directories.get(current)
    const actual = capturePnpmDirectory(current)
    if (
      !expected ||
      expected.dev !== actual.dev ||
      expected.ino !== actual.ino
    ) {
      throw new Error(
        `Pnpm input directory changed. Where: ${current}. Wanted the directory recorded during discovery. Retry after edits finish.`,
      )
    }
    if (current === scan.root) {
      return
    }
    current = pnpmPath.dirname(current)
  }
}

export function pnpmEcosystemFiles(root, ownership, options = {}) {
  return collectPnpmEcosystemFiles(root, ownership, options).files
}

function collectPnpmEcosystemFiles(root, ownership, config) {
  const names = new Set()
  if (ownership.cargo) {
    names.add('Cargo.toml')
    names.add('Cargo.lock')
  }
  if (ownership.python) {
    names.add('pyproject.toml')
    names.add('pylock.toml')
  }
  if (names.size === 0) {
    return {
      __proto__: null,
      root,
      directories: new Map(),
      files: [],
    }
  }
  root = pnpmRealpathSync(root)
  const scan = {
    root,
    directories: new Map([[root, capturePnpmDirectory(root)]]),
  }
  const { maxEntries = PNPM_INPUT_MAX_ENTRIES } = {
    __proto__: null,
    ...config,
  }
  const stack = ['']
  const files = []
  let count = 0
  while (stack.length) {
    const relative = stack.pop()
    if (relative === undefined) {
      break
    }
    const directoryPath = pnpmPath.join(root, relative)
    assertPnpmDirectories(directoryPath, scan)
    const directory = pnpmOpendirSync(directoryPath)
    try {
      assertPnpmDirectories(directoryPath, scan)
      let entry
      while ((entry = directory.readSync()) !== null) {
        count += 1
        if (count > maxEntries) {
          throw new Error(
            `Cannot fingerprint pnpm ecosystem inputs. Where: ${root}. Saw more than ${maxEntries} entries. Fix the workspace layout or its vendor exclusions.`,
          )
        }
        if (entry.isSymbolicLink()) {
          continue
        }
        const child = relative ? `${relative}/${entry.name}` : entry.name
        if (entry.isDirectory()) {
          if (isPnpmInputDirectory(entry.name)) {
            const childPath = pnpmPath.join(root, child)
            scan.directories.set(childPath, capturePnpmDirectory(childPath))
            stack.push(child)
          }
        } else if (entry.isFile() && names.has(entry.name)) {
          files.push(child)
        }
      }
    } finally {
      directory.closeSync()
    }
  }
  return {
    __proto__: null,
    ...scan,
    files: files.toSorted(),
  }
}

function readPnpmInput(file, remainingBytes, scan) {
  const parent = pnpmPath.dirname(file)
  assertPnpmDirectories(parent, scan)
  const metadata = pnpmLstatSync(file)
  if (!metadata.isFile() || metadata.size > remainingBytes) {
    throw new Error(
      `Cannot fingerprint pnpm ecosystem input. Where: ${file}. Wanted a regular file within the remaining ${remainingBytes} bytes. Fix the workspace inputs.`,
    )
  }
  const flags =
    pnpmConstants.O_RDONLY |
    (pnpmConstants.O_NOFOLLOW ?? 0) |
    (pnpmConstants.O_NONBLOCK ?? 0)
  const descriptor = pnpmOpenSync(file, flags)
  try {
    assertPnpmDirectories(parent, scan)
    const opened = pnpmFstatSync(descriptor)
    if (
      !opened.isFile() ||
      opened.size !== metadata.size ||
      opened.ino !== metadata.ino ||
      opened.dev !== metadata.dev
    ) {
      throw new Error(
        `Pnpm input changed while opening. Where: ${file}. Wanted a stable regular file. Retry after edits finish.`,
      )
    }
    const bytes = Buffer.alloc(metadata.size)
    let offset = 0
    while (offset < bytes.length) {
      const count = pnpmReadSync(
        descriptor,
        bytes,
        offset,
        bytes.length - offset,
        offset,
      )
      if (count === 0) {
        throw new Error(
          `Pnpm input changed while reading. Where: ${file}. Wanted complete file bytes. Retry after edits finish.`,
        )
      }
      offset += count
    }
    if (pnpmReadSync(descriptor, Buffer.alloc(1), 0, 1, offset) !== 0) {
      throw new Error(
        `Pnpm input grew while reading. Where: ${file}. Wanted stable file bytes. Retry after edits finish.`,
      )
    }
    assertPnpmDirectories(parent, scan)
    return bytes
  } finally {
    pnpmCloseSync(descriptor)
  }
}

export function pnpmEcosystemFingerprint(root, options = {}) {
  const ownership = readPnpmEcosystemOwnership(root, options)
  if (!ownership.cargo && !ownership.python) {
    return ''
  }
  const hash = pnpmCrypto.createHash('sha256').update(JSON.stringify(ownership))
  const maxBytes = options.maxBytes ?? PNPM_INPUT_MAX_BYTES
  let totalBytes = 0
  const scan = collectPnpmEcosystemFiles(root, ownership, options)
  for (const relative of scan.files) {
    const bytes = readPnpmInput(
      pnpmPath.join(scan.root, relative),
      maxBytes - totalBytes,
      scan,
    )
    totalBytes += bytes.length
    hash.update(JSON.stringify([relative, bytes.length])).update(bytes)
  }
  return hash.digest('hex')
}
