// Fleet check — the committed `_dispatch/dispatch-table.mts` matches a fresh
// regen from the hook dirs present in THIS tree.
//
// The dispatch table is generated by make-hook-dispatch.mts from the bundle-safe
// hooks under .claude/hooks/fleet/. If a hook is added or removed without
// regenerating — or a byte-cascaded table references a hook dir that does not
// exist in this tree (the concurrent-cargo-build-guard dangle that shipped a
// table importing an absent hook) — the on-disk table drifts from a fresh
// regen, and the rolldown bundle silently drops or fails to resolve that hook.
//
// This is the commit-time twin of `make-hook-dispatch.mts --check`: it
// regenerates in-process over the current hook dirs and fails (exit 1) when the
// committed table differs, naming the rebuild command. Per-tree: it checks
// whatever tree it runs in (the wheelhouse live mirror, or a member's), so a
// cascade that leaves a tree's table out of sync with its hooks fails loud.
//
// Usage: node scripts/fleet/check/dispatch-table-is-current.mts [--quiet]

import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'

import {
  DISPATCH_MANIFEST_PATH,
  DISPATCH_TABLE_PATH,
  FLEET_HOOKS_DIR,
  generateDispatchManifestSource,
  generateDispatchTableSource,
} from '../make-hook-dispatch.mts'
import { REPO_ROOT } from '../paths.mts'
import { isMainModule } from '../_shared/is-main-module.mts'

const logger = getDefaultLogger()

export function dispatchTableIsCurrent(
  hooksDir: string = FLEET_HOOKS_DIR,
  dispatchPath: string = DISPATCH_TABLE_PATH,
): boolean {
  const generated = generateDispatchTableSource(hooksDir)
  const onDisk = existsSync(dispatchPath)
    ? readFileSync(dispatchPath, 'utf8')
    : ''
  return onDisk === generated
}

/**
 * The committed dep-0 dispatch manifest (`_shared/dispatch-manifest.json`, the
 * bootstrap dispatcher's routing table) matches a fresh regen. A stale manifest
 * leaves a hook silently INERT on the bootstrap path even when the bundled
 * table carries it — the exact drift that made ~30 hooks (including critical
 * guards) dead on that path.
 */
export function dispatchManifestIsCurrent(
  hooksDir: string = FLEET_HOOKS_DIR,
  manifestPath: string = DISPATCH_MANIFEST_PATH,
): boolean {
  const generated = generateDispatchManifestSource(hooksDir)
  const onDisk = existsSync(manifestPath)
    ? readFileSync(manifestPath, 'utf8')
    : ''
  return onDisk === generated
}

function main(): void {
  const quiet = process.argv.includes('--quiet')
  if (!dispatchTableIsCurrent()) {
    logger.fail(
      '[check-dispatch-table-is-current] _dispatch/dispatch-table.mts drifts from a fresh regen.',
    )
    logger.error(`  Where: ${path.relative(REPO_ROOT, DISPATCH_TABLE_PATH)}`)
    logger.error(
      '  Saw:   the committed table differs from a regen over the current hook dirs',
    )
    logger.error(
      '         (a hook added/removed without regenerating, or a byte-cascaded table',
    )
    logger.error(
      '         referencing a hook dir absent from this tree — the concurrent-cargo dangle).',
    )
    logger.error(
      '  Fix:   node scripts/fleet/build-hook-bundle.mts  (regenerates the table + rebuilds the bundle), then commit.',
    )
    process.exitCode = 1
    return
  }
  if (!dispatchManifestIsCurrent()) {
    logger.fail(
      '[check-dispatch-table-is-current] _shared/dispatch-manifest.json drifts from a fresh regen.',
    )
    logger.error(
      `Where: ${path.relative(REPO_ROOT, DISPATCH_MANIFEST_PATH)}\n` +
        'Saw:   the committed manifest differs from a regen over the current hook dirs\n' +
        '       (a hook added/removed without regenerating — the dep-0 bootstrap dispatcher\n' +
        '       routes off this manifest, so a drifted hook is silently inert on that path).\n' +
        'Fix:   node scripts/fleet/build-hook-bundle.mts  (regenerates the table + manifest), then commit.',
    )
    process.exitCode = 1
    return
  }
  if (!quiet) {
    logger.success(
      '[check-dispatch-table-is-current] dispatch table + manifest match a fresh regen.',
    )
  }
}

if (isMainModule(import.meta.url)) {
  main()
}
