// Fleet check — the committed `_dispatch/dispatch-table.mts` matches a fresh
// regen from the hook dirs present in THIS tree.
//
// The dispatch table is generated by make-hook-dispatch.mts from the bundle-safe
// hooks under .claude/hooks/fleet/. If a hook is added or removed without
// regenerating — or a byte-cascaded table references a hook dir that does not
// exist in this tree (the concurrent-cargo-build-guard dangle that shipped a
// table importing an absent hook) — the on-disk table drifts from a fresh
// regen, and the rolldown bundle silently drops or fails to resolve that hook.
//
// This is the commit-time twin of `make-hook-dispatch.mts --check`: it
// regenerates in-process over the current hook dirs and fails (exit 1) when the
// committed table differs, naming the rebuild command. Per-tree: it checks
// whatever tree it runs in (the wheelhouse live mirror, or a member's), so a
// cascade that leaves a tree's table out of sync with its hooks fails loud.
//
// Usage: node scripts/fleet/check/dispatch-table-is-current.mts [--quiet]

import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'

import {
  DISPATCH_TABLE_PATH,
  FLEET_HOOKS_DIR,
  generateDispatchTableSource,
} from '../make-hook-dispatch.mts'
import { REPO_ROOT } from '../paths.mts'

const logger = getDefaultLogger()

export function dispatchTableIsCurrent(
  hooksDir: string = FLEET_HOOKS_DIR,
  dispatchPath: string = DISPATCH_TABLE_PATH,
): boolean {
  const generated = generateDispatchTableSource(hooksDir)
  const onDisk = existsSync(dispatchPath)
    ? readFileSync(dispatchPath, 'utf8')
    : ''
  return onDisk === generated
}

function main(): void {
  const quiet = process.argv.includes('--quiet')
  if (!dispatchTableIsCurrent()) {
    logger.fail(
      '[check-dispatch-table-is-current] _dispatch/dispatch-table.mts drifts from a fresh regen.',
    )
    logger.error(`  Where: ${path.relative(REPO_ROOT, DISPATCH_TABLE_PATH)}`)
    logger.error(
      '  Saw:   the committed table differs from a regen over the current hook dirs',
    )
    logger.error(
      '         (a hook added/removed without regenerating, or a byte-cascaded table',
    )
    logger.error(
      '         referencing a hook dir absent from this tree — the concurrent-cargo dangle).',
    )
    logger.error(
      '  Fix:   node scripts/fleet/build-hook-bundle.mts  (regenerates the table + rebuilds the bundle), then commit.',
    )
    process.exitCode = 1
    return
  }
  if (!quiet) {
    logger.success(
      '[check-dispatch-table-is-current] dispatch table matches a fresh regen.',
    )
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
