#!/usr/bin/env node
/*
 * @file `check --all` gate: every committed GENERATED artifact still equals
 *   what its generator renders today. Reads the registry in
 *   `_shared/generated-artifacts.mts`.
 *
 *   Mechanism is regenerate-and-compare, not a pure re-render. Most fleet
 *   generators write their output directly and expose no render function, so
 *   the gate snapshots each output's bytes, runs the generator, compares, and
 *   puts the snapshot back. It is side-effect free by default. `--fix` keeps
 *   the regenerated bytes instead.
 *
 *   Reports every stale artifact in one pass. A gate that stops at the first
 *   failure turns one run into N runs, which is the loop
 *   `preflight-before-the-gate` exists to kill.
 *
 *   Exit: 0 — every artifact current, or nothing to check; 1 — one or more
 *   stale, or a generator failed.
 *
 *   Usage: node scripts/fleet/check/generated-artifacts-are-current.mts
 *          node scripts/fleet/check/generated-artifacts-are-current.mts --fix
 *          node scripts/fleet/check/generated-artifacts-are-current.mts --self-test
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { spawn } from '@socketsecurity/lib-stable/process/spawn/child'

import { isMainModule } from '../process/is-main-module.mts'
import { runMain } from '../process/run-main.mts'
import { REPO_ROOT, resolveSyncScaffoldingManifestDir } from '../paths.mts'
import { artifactsForTier } from './_shared/generated-artifacts.mts'

import type { ScriptMeta } from '../process/run-main.mts'
import type { GeneratedArtifact } from './_shared/generated-artifacts.mts'

/**
 * An output's bytes, or undefined when the generator creates it fresh.
 */
type Snapshot = ReadonlyMap<string, string | undefined>

/**
 * Whether this tree is the wheelhouse, which decides if wheelhouse-tier
 * entries are checkable. Keyed on the commit-cascade manifest directory,
 * the thing those generators actually read.
 */
export function isWheelhouseCheckout(repoRoot: string): boolean {
  return existsSync(resolveSyncScaffoldingManifestDir(repoRoot))
}

/**
 * Read every output of `artifact`, tolerating one that does not exist yet.
 */
export function snapshotOutputs(
  repoRoot: string,
  artifact: GeneratedArtifact,
): Snapshot {
  const snap = new Map<string, string | undefined>()
  for (const rel of artifact.outputs) {
    const abs = path.join(repoRoot, rel)
    snap.set(rel, existsSync(abs) ? readFileSync(abs, 'utf8') : undefined)
  }
  return snap
}

/**
 * Put every output back the way `snapshotOutputs` found it.
 *
 * An output the generator creates from nothing stays on disk. The gate
 * reports it as stale, and discarding a file the operator can now see is a
 * surprise the report cannot undo.
 */
export function restoreOutputs(repoRoot: string, snap: Snapshot): void {
  for (const [rel, before] of snap) {
    if (before === undefined) {
      continue
    }
    writeFileSync(path.join(repoRoot, rel), before, 'utf8')
  }
}

/**
 * The outputs whose bytes changed when the generator ran.
 */
export function staleOutputs(repoRoot: string, snap: Snapshot): string[] {
  const stale: string[] = []
  for (const [rel, before] of snap) {
    const abs = path.join(repoRoot, rel)
    const after = existsSync(abs) ? readFileSync(abs, 'utf8') : undefined
    if (after !== before) {
      stale.push(rel)
    }
  }
  return stale
}

/**
 * The What/Where/Saw/Why/Fix block for one stale artifact.
 */
export function staleReport(
  artifact: GeneratedArtifact,
  stale: readonly string[],
): string {
  return [
    `What: the committed "${artifact.id}" artifact is STALE.`,
    `Where: ${stale.join(', ')}`,
    `Saw: the committed bytes differ from what ${artifact.script} renders now.`,
    `Why: ${artifact.consequence}.`,
    `Fix: node ${artifact.script}`,
  ].join('\n')
}

/**
 * The two tiers this gate runs in. `compare` is side-effect free: it puts every
 * snapshotted output back. `regenerate` (`--fix`) keeps the freshly rendered
 * bytes on disk instead.
 */
export type ArtifactRunMode = 'compare' | 'regenerate'

/**
 * The verdict for one artifact. `failure` carries the ready-to-print block for
 * a missing generator, a generator that exited non-zero, or (in `compare` mode)
 * a stale output. `isStale` is set whenever the bytes moved, in either mode, so
 * `--fix` can still name what it regenerated.
 */
export interface ArtifactInspection {
  readonly failure?: string | undefined
  readonly isStale: boolean
}

/**
 * Regenerate one artifact and compare. In `compare` mode every snapshotted
 * output goes back before this returns, including on the generator-failed path.
 */
export async function inspectArtifact(
  artifact: GeneratedArtifact,
  mode: ArtifactRunMode,
): Promise<ArtifactInspection> {
  const scriptAbs = path.join(REPO_ROOT, artifact.script)
  if (!existsSync(scriptAbs)) {
    return {
      failure: [
        `What: the generator for "${artifact.id}" is missing.`,
        `Where: ${artifact.script}`,
        'Saw: no file at that path; wanted the generator the registry names.',
        'Fix: correct the `script` field in scripts/fleet/check/_shared/generated-artifacts.mts.',
      ].join('\n'),
      isStale: false,
    }
  }
  const before = snapshotOutputs(REPO_ROOT, artifact)
  // `spawn` rejects on a non-zero exit, so the catch and the code check are
  // the same failure arriving by two routes.
  let exitCode: number | undefined
  try {
    const result = await spawn('node', [scriptAbs], {
      cwd: REPO_ROOT,
      stdioString: true,
    })
    exitCode = result.code ?? 0
  } catch {
    exitCode = 1
  }
  if (exitCode !== 0) {
    restoreOutputs(REPO_ROOT, before)
    return {
      failure: [
        `What: the generator for "${artifact.id}" exited ${exitCode}.`,
        `Where: ${artifact.script}`,
        'Saw: a non-zero exit, so its output could not be compared.',
        'Fix: run it directly and read the error.',
      ].join('\n'),
      isStale: false,
    }
  }
  const stale = staleOutputs(REPO_ROOT, before)
  if (!stale.length) {
    return { isStale: false }
  }
  if (mode === 'regenerate') {
    return { isStale: true }
  }
  restoreOutputs(REPO_ROOT, before)
  return { failure: staleReport(artifact, stale), isStale: true }
}

/**
 * Inspect every artifact in one pass. A gate that stops at the first failure
 * turns one run into N runs, so every artifact is visited and its verdict
 * collected.
 */
export async function inspectArtifacts(
  artifacts: readonly GeneratedArtifact[],
  mode: ArtifactRunMode,
): Promise<{ failures: string[]; staleIds: string[] }> {
  const logger = getDefaultLogger()
  const failures: string[] = []
  const staleIds: string[] = []
  for (const artifact of artifacts) {
    const inspection = await inspectArtifact(artifact, mode)
    if (inspection.isStale) {
      staleIds.push(artifact.id)
      if (mode === 'regenerate') {
        logger.log(
          `[generated-artifacts-are-current] regenerated ${artifact.id}`,
        )
      }
    }
    if (inspection.failure) {
      failures.push(inspection.failure)
    }
  }
  return { failures, staleIds }
}

/**
 * The `--self-test` arm: perturb one committed output and prove the comparison
 * still notices. Returns the failure message, or `''` when the gate proved
 * itself. Without an arm like this a gate that silently stopped comparing would
 * report green forever.
 */
export function selfTestFailure(
  artifacts: readonly GeneratedArtifact[],
): string {
  const probe = artifacts[0]!
  const snap = snapshotOutputs(REPO_ROOT, probe)
  const { 0: firstRel } = [...snap.keys()]
  const original = snap.get(firstRel!)
  if (original === undefined) {
    return '[generated-artifacts-are-current] SELF-TEST FAILED: the probe artifact has no committed output to perturb.'
  }
  writeFileSync(
    path.join(REPO_ROOT, firstRel!),
    `${original}\n// self-test perturbation\n`,
    'utf8',
  )
  const detected = staleOutputs(REPO_ROOT, snap).length > 0
  restoreOutputs(REPO_ROOT, snap)
  if (!detected) {
    return '[generated-artifacts-are-current] SELF-TEST FAILED: a perturbed artifact went undetected, so this gate cannot catch the drift it exists for.'
  }
  return ''
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
): Promise<number> {
  const logger = getDefaultLogger()
  const fix = argv.includes('--fix')
  const quiet = argv.includes('--quiet')
  const selfTest = argv.includes('--self-test')
  const artifacts = artifactsForTier(isWheelhouseCheckout(REPO_ROOT))

  if (!artifacts.length) {
    logger.log(
      '[generated-artifacts-are-current] no checkable artifacts in this tree.',
    )
    return 0
  }

  const mode: ArtifactRunMode = fix ? 'regenerate' : 'compare'
  const { failures, staleIds } = await inspectArtifacts(artifacts, mode)

  if (selfTest) {
    const selfTestMessage = selfTestFailure(artifacts)
    if (selfTestMessage) {
      logger.error(selfTestMessage)
      return 1
    }
  }

  if (fix) {
    logger.success(
      staleIds.length
        ? `[generated-artifacts-are-current] regenerated ${staleIds.length} stale artifact(s): ${staleIds.join(', ')}. Commit the result.`
        : '[generated-artifacts-are-current] every artifact was already current.',
    )
    return 0
  }

  if (failures.length) {
    logger.error('[generated-artifacts-are-current] FAILED:')
    logger.group()
    for (let i = 0, { length } = failures; i < length; i += 1) {
      const failure = failures[i]!
      logger.fail(failure)
    }
    logger.groupEnd()
    return 1
  }

  // `--quiet` silences the PASS line only. A failure and the `--fix` receipt
  // both still print: a check that can be told to hide its own red is a check
  // a caller can neutralize by accident.
  if (!quiet) {
    logger.success(
      `[generated-artifacts-are-current] ${artifacts.length} generated artifact(s) match their generators${selfTest ? '. Self-test passed.' : '.'}`,
    )
  }
  return 0
}

const SCRIPT_META: ScriptMeta = {
  describe:
    'checks every committed generated artifact still matches what its generator renders',
  help: 'Usage: node scripts/fleet/check/generated-artifacts-are-current.mts [--fix] [--self-test]',
}

if (isMainModule(import.meta.url)) {
  runMain(main, SCRIPT_META)
}
