#!/usr/bin/env node
/*
 * @file `check --all` gate: every committed GENERATED artifact still equals
 *   what its generator renders today. Reads the registry in
 *   `_shared/generated-artifacts.mts`.
 *
 *   Mechanism is regenerate-and-compare, not a pure re-render. Most fleet
 *   generators write their output directly and expose no render function, so
 *   the gate snapshots each output's bytes, runs the generator, compares, and
 *   puts the snapshot back. It is side-effect free by default. `--fix` keeps
 *   the regenerated bytes instead.
 *
 *   Reports every stale artifact in one pass. A gate that stops at the first
 *   failure turns one run into N runs, which is the loop
 *   `preflight-before-the-gate` exists to kill.
 *
 *   Exit: 0 — every artifact current, or nothing to check; 1 — one or more
 *   stale, or a generator failed.
 *
 *   Usage: node scripts/fleet/check/generated-artifacts-are-current.mts
 *          node scripts/fleet/check/generated-artifacts-are-current.mts --fix
 *          node scripts/fleet/check/generated-artifacts-are-current.mts --self-test
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { spawn } from '@socketsecurity/lib-stable/process/spawn/child'

import { isMainModule } from '../_shared/is-main-module.mts'
import { runMain } from '../_shared/run-main.mts'
import { REPO_ROOT, resolveSyncScaffoldingManifestDir } from '../paths.mts'
import { artifactsForTier } from './_shared/generated-artifacts.mts'

import type { ScriptMeta } from '../_shared/run-main.mts'
import type { GeneratedArtifact } from './_shared/generated-artifacts.mts'

/**
 * An output's bytes, or undefined when the generator creates it fresh.
 */
type Snapshot = ReadonlyMap<string, string | undefined>

/**
 * Whether this tree is the wheelhouse, which decides if wheelhouse-tier
 * entries are checkable. Keyed on the sync-scaffolding manifest directory,
 * the thing those generators actually read.
 */
export function isWheelhouseCheckout(repoRoot: string): boolean {
  return existsSync(resolveSyncScaffoldingManifestDir(repoRoot))
}

/**
 * Read every output of `artifact`, tolerating one that does not exist yet.
 */
export function snapshotOutputs(
  repoRoot: string,
  artifact: GeneratedArtifact,
): Snapshot {
  const snap = new Map<string, string | undefined>()
  for (const rel of artifact.outputs) {
    const abs = path.join(repoRoot, rel)
    snap.set(rel, existsSync(abs) ? readFileSync(abs, 'utf8') : undefined)
  }
  return snap
}

/**
 * Put every output back the way `snapshotOutputs` found it.
 *
 * An output the generator creates from nothing stays on disk. The gate
 * reports it as stale, and discarding a file the operator can now see is a
 * surprise the report cannot undo.
 */
export function restoreOutputs(repoRoot: string, snap: Snapshot): void {
  for (const [rel, before] of snap) {
    if (before === undefined) {
      continue
    }
    writeFileSync(path.join(repoRoot, rel), before, 'utf8')
  }
}

/**
 * The outputs whose bytes changed when the generator ran.
 */
export function staleOutputs(repoRoot: string, snap: Snapshot): string[] {
  const stale: string[] = []
  for (const [rel, before] of snap) {
    const abs = path.join(repoRoot, rel)
    const after = existsSync(abs) ? readFileSync(abs, 'utf8') : undefined
    if (after !== before) {
      stale.push(rel)
    }
  }
  return stale
}

/**
 * The What/Where/Saw/Why/Fix block for one stale artifact.
 */
export function staleReport(
  artifact: GeneratedArtifact,
  stale: readonly string[],
): string {
  return [
    `What: the committed "${artifact.id}" artifact is STALE.`,
    `Where: ${stale.join(', ')}`,
    `Saw: the committed bytes differ from what ${artifact.script} renders now.`,
    `Why: ${artifact.consequence}.`,
    `Fix: node ${artifact.script}`,
  ].join('\n')
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
): Promise<number> {
  const logger = getDefaultLogger()
  const fix = argv.includes('--fix')
  const quiet = argv.includes('--quiet')
  const selfTest = argv.includes('--self-test')
  const artifacts = artifactsForTier(isWheelhouseCheckout(REPO_ROOT))

  if (!artifacts.length) {
    logger.log(
      '[generated-artifacts-are-current] no checkable artifacts in this tree.',
    )
    return 0
  }

  const failures: string[] = []
  const staleIds: string[] = []

  for (const artifact of artifacts) {
    const scriptAbs = path.join(REPO_ROOT, artifact.script)
    if (!existsSync(scriptAbs)) {
      failures.push(
        [
          `What: the generator for "${artifact.id}" is missing.`,
          `Where: ${artifact.script}`,
          'Saw: no file at that path; wanted the generator the registry names.',
          'Fix: correct the `script` field in scripts/fleet/check/_shared/generated-artifacts.mts.',
        ].join('\n'),
      )
      continue
    }

    const before = snapshotOutputs(REPO_ROOT, artifact)
    // `spawn` rejects on a non-zero exit, so the catch and the code check are
    // the same failure arriving by two routes.
    let exitCode: number | undefined
    try {
      const result = await spawn('node', [scriptAbs], {
        cwd: REPO_ROOT,
        stdioString: true,
      })
      exitCode = result.code ?? 0
    } catch {
      exitCode = 1
    }
    if (exitCode !== 0) {
      restoreOutputs(REPO_ROOT, before)
      failures.push(
        [
          `What: the generator for "${artifact.id}" exited ${exitCode}.`,
          `Where: ${artifact.script}`,
          'Saw: a non-zero exit, so its output could not be compared.',
          'Fix: run it directly and read the error.',
        ].join('\n'),
      )
      continue
    }

    const stale = staleOutputs(REPO_ROOT, before)
    if (!stale.length) {
      continue
    }
    staleIds.push(artifact.id)
    if (fix) {
      logger.log(`[generated-artifacts-are-current] regenerated ${artifact.id}`)
      continue
    }
    restoreOutputs(REPO_ROOT, before)
    failures.push(staleReport(artifact, stale))
  }

  // `--self-test` proves the gate can still fail. Without an arm like this a
  // gate that silently stopped comparing would report green forever.
  if (selfTest) {
    const probe = artifacts[0]!
    const snap = snapshotOutputs(REPO_ROOT, probe)
    const [firstRel] = [...snap.keys()]
    const original = snap.get(firstRel!)
    if (original === undefined) {
      logger.error(
        '[generated-artifacts-are-current] SELF-TEST FAILED: the probe artifact has no committed output to perturb.',
      )
      return 1
    }
    writeFileSync(
      path.join(REPO_ROOT, firstRel!),
      `${original}\n// self-test perturbation\n`,
      'utf8',
    )
    const detected = staleOutputs(REPO_ROOT, snap).length > 0
    restoreOutputs(REPO_ROOT, snap)
    if (!detected) {
      logger.error(
        '[generated-artifacts-are-current] SELF-TEST FAILED: a perturbed artifact went undetected, so this gate cannot catch the drift it exists for.',
      )
      return 1
    }
  }

  if (fix) {
    logger.success(
      staleIds.length
        ? `[generated-artifacts-are-current] regenerated ${staleIds.length} stale artifact(s): ${staleIds.join(', ')}. Commit the result.`
        : '[generated-artifacts-are-current] every artifact was already current.',
    )
    return 0
  }

  if (failures.length) {
    logger.error('[generated-artifacts-are-current] FAILED:')
    logger.group()
    for (let i = 0, { length } = failures; i < length; i += 1) {
      const failure = failures[i]!
      logger.fail(failure)
    }
    logger.groupEnd()
    return 1
  }

  logger.success(
    `[generated-artifacts-are-current] ${artifacts.length} generated artifact(s) match their generators${selfTest ? '. Self-test passed.' : '.'}`,
  )
  return 0
}

const SCRIPT_META: ScriptMeta = {
  describe:
    'checks every committed generated artifact still matches what its generator renders',
  help: 'Usage: node scripts/fleet/check/generated-artifacts-are-current.mts [--fix] [--self-test]',
}

if (isMainModule(import.meta.url)) {
  runMain(main, SCRIPT_META)
}
