#!/usr/bin/env node
/**
 * @file `check --all` gate: the gh-aw compile surface is CLOSED. Every
 *   gh-aw-generated file in the tree under a `.github/workflows/` dir —
 *   tracked or untracked, compiled `.lock.yml` files AND compiler-emitted
 *   plain `.yml` like `agentics-maintenance.yml`, identified by their
 *   generated-by headers — must correspond to a declared `.md` source or an
 *   explicit SANCTIONED_GHAW_EMISSIONS entry. A bare `gh aw compile` can emit
 *   NEW workflow files nobody decided on — v0.83.2's
 *   `pkg/workflow/maintenance_workflow.go` emitted an undeclared
 *   `agentics-maintenance.yml` a session had to notice and discard by hand.
 *   This gate makes adoption an explicit allowlist edit, never a drive-by:
 *   an undeclared emission goes red with the two legal moves named. The
 *   sanctioned compile path — `sync-gh-aw-action-pins.mts` — imports the same
 *   pure surface law to delete undeclared emissions after every compile.
 *   Pure node, no gh-aw dependency. Exit 0 — surface closed, or no gh-aw
 *   files at all; 1 — at least one undeclared emission.
 *   Usage: node scripts/fleet/check/gh-aw-emissions-are-declared.mts [--quiet]
 */

// oxlint-disable-next-line socket/prefer-async-spawn -- sync check; needs typed string stdout from `git ls-files`, no async.
import { spawnSync } from '@socketsecurity/lib-stable/process/spawn/child'
import { readFileSync } from 'node:fs'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { normalizePath } from '@socketsecurity/lib-stable/paths/normalize'

import { isMainModule } from '../_shared/is-main-module.mts'
import { runMain } from '../_shared/run-main.mts'

import type { ScriptMeta } from '../_shared/run-main.mts'

const logger = getDefaultLogger()

// The ONLY gh-aw-generated files allowed to exist WITHOUT a sibling `.md`
// source: repo-root-relative path tails, matched mirror-agnostically so one
// entry covers the live copy and the `template/base/` mirror. Adopting a
// compiler side-emission is a deliberate edit here — one entry per file, with
// a dated one-line justification comment. Empty by design: nothing is
// currently adopted, and the last drive-by, v0.83.2's
// `agentics-maintenance.yml`, was discarded rather than adopted.
export const SANCTIONED_GHAW_EMISSIONS: readonly string[] = []

/**
 * True when file text carries a gh-aw generated-by header. Two markers, both
 * from the compiler's own writers: the `# gh-aw-metadata:` line every
 * compiled `.lock.yml` opens with, and `GenerateWorkflowHeader`'s disclaimer
 * line — `# This file was automatically generated by …` plus the gh-aw
 * debug-skill pointer — which every compiler side-emission carries whatever
 * its `generatedBy` label says, `maintenance_workflow.go` included.
 */
export function isGhAwGeneratedText(text: string): boolean {
  const head = text.slice(0, 4096)
  // Compiled-lock marker: the gh-aw-metadata header line.
  if (/^#\s*gh-aw-metadata:/mu.test(head)) {
    return true
  }
  // Side-emission marker: the generated-by disclaimer with the gh-aw
  // debug-skill pointer that GenerateWorkflowHeader always appends.
  return (
    /^# This file was automatically generated/mu.test(head) &&
    head.includes('github.com/github/gh-aw')
  )
}

export interface GhAwSurfaceFile {
  // Repo-relative path of a .yml/.yaml file under a .github/workflows/ dir.
  relPath: string
  // File content — only the head is inspected for generated-by markers.
  text: string
}

export interface GhAwSurfaceConfig {
  files: readonly GhAwSurfaceFile[]
  // Repo-relative paths of gh-aw workflow .md sources — a `.lock.yml` is
  // declared when its same-dir, same-stem `.md` is in this set.
  mdSourceRelPaths: readonly string[]
  sanctionedTails: readonly string[]
}

/**
 * Pure surface law: which gh-aw-generated files are UNDECLARED. A generated
 * file is declared when it is a `.lock.yml` whose sibling `.md` source
 * exists, or when its path tail-matches a sanctioned emission entry.
 * Non-generated files — hand-authored workflows, delegators — never appear.
 * Returns sorted repo-relative paths.
 */
export function findUndeclaredGhAwEmissions(
  config: GhAwSurfaceConfig,
): string[] {
  const { files, mdSourceRelPaths, sanctionedTails } = {
    __proto__: null,
    ...config,
  } as GhAwSurfaceConfig
  const mdSet = new Set(mdSourceRelPaths.map(p => normalizePath(p)))
  const undeclared: string[] = []
  for (const { relPath, text } of files) {
    if (!isGhAwGeneratedText(text)) {
      continue
    }
    const p = normalizePath(relPath)
    if (
      p.endsWith('.lock.yml') &&
      mdSet.has(p.replace(/\.lock\.yml$/u, '.md'))
    ) {
      continue
    }
    if (sanctionedTails.some(tail => p === tail || p.endsWith(`/${tail}`))) {
      continue
    }
    undeclared.push(p)
  }
  return undeclared.toSorted()
}

// Enumerate repo-relative paths under any `.github/workflows/` dir — tracked
// plus untracked-unignored, so a fresh drive-by emission that nobody staged
// still trips the gate. Returns undefined when git is unavailable.
function listWorkflowTreeFiles(): string[] | undefined {
  const out = new Set<string>()
  const argSets = [
    ['ls-files', '--', '*.github/workflows/*'],
    [
      'ls-files',
      '--others',
      '--exclude-standard',
      '--',
      '*.github/workflows/*',
    ],
  ]
  for (let i = 0, { length } = argSets; i < length; i += 1) {
    const args = argSets[i]!
    const r = spawnSync('git', args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      stdioString: true,
    })
    if (r.status !== 0 || typeof r.stdout !== 'string') {
      return undefined
    }
    const lines = r.stdout.split(/\r?\n/u)
    for (let j = 0, len = lines.length; j < len; j += 1) {
      const rel = lines[j]!.trim()
      if (rel) {
        out.add(rel)
      }
    }
  }
  return [...out].toSorted()
}

function readFileSafe(file: string): string {
  try {
    return readFileSync(file, 'utf8')
  } catch {
    return ''
  }
}

export function main(): void {
  const treeFiles = listWorkflowTreeFiles()
  if (treeFiles === undefined) {
    // git unavailable — vacuous, never a false-red on a non-git tree.
    process.exitCode = 0
    return
  }
  // A gh-aw workflow source always opens with YAML frontmatter; plain docs
  // living beside the workflows do not — same gate as gh-aw-locks-are-current.
  const mdSourceRelPaths = treeFiles.filter(
    p => p.endsWith('.md') && readFileSafe(p).startsWith('---'),
  )
  const files: GhAwSurfaceFile[] = treeFiles
    .filter(p => /\.ya?ml$/u.test(p))
    .map(relPath => ({ relPath, text: readFileSafe(relPath) }))
  const undeclared = findUndeclaredGhAwEmissions({
    files,
    mdSourceRelPaths,
    sanctionedTails: SANCTIONED_GHAW_EMISSIONS,
  })
  if (undeclared.length === 0) {
    if (!process.argv.includes('--quiet')) {
      logger.log(
        files.length === 0
          ? 'gh-aw emissions: no workflow yml files in this repo — not applicable.'
          : `gh-aw emissions: surface closed — every gh-aw-generated file maps to a declared .md source (${files.length} yml file(s) scanned).`,
      )
    }
    process.exitCode = 0
    return
  }
  logger.fail(
    `[gh-aw-emissions] ${undeclared.length} undeclared gh-aw emission(s) in the tree:`,
  )
  logger.group()
  for (const p of undeclared) {
    logger.error(`✗ ${p}`)
  }
  logger.error(
    'What: a gh-aw-generated workflow file exists with no declared .md source',
  )
  logger.error(
    '      and no SANCTIONED_GHAW_EMISSIONS entry — a bare `gh aw compile`',
  )
  logger.error('      side-emission nobody decided to adopt.')
  logger.error('Where: the path(s) above.')
  logger.error(
    'Saw: a generated-by gh-aw header on a file outside the declared surface;',
  )
  logger.error(
    '     wanted every gh-aw file to be a compiled lock of a .md source or an',
  )
  logger.error('     explicit allowlist entry.')
  logger.error(
    'Fix: two legal moves — adopt it deliberately by adding its path',
  )
  logger.error('     tail to SANCTIONED_GHAW_EMISSIONS in')
  logger.error(
    '     scripts/fleet/check/gh-aw-emissions-are-declared.mts with a dated',
  )
  logger.error('     one-line justification, or delete the file.')
  logger.groupEnd()
  process.exitCode = 1
}

const SCRIPT_META: ScriptMeta = {
  describe:
    'verifies every gh-aw-generated workflow file maps to a declared .md source or a sanctioned emission',
  help: `Usage: node scripts/fleet/check/gh-aw-emissions-are-declared.mts [flags]

  --quiet  suppress the success message`,
}

/* c8 ignore start - entrypoint guard; exercised via subprocess */
if (isMainModule(import.meta.url)) {
  runMain(main, SCRIPT_META)
}
/* c8 ignore stop */
