/**
 * @file Extraction + rendering helpers for the API docs generator. Houses the
 *   domain group definitions, quota labels, the method extractor that walks the
 *   SDK class source, and the markdown renderers consumed by
 *   scripts/repo/gen-api-docs.mts.
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { findUpSync } from '@socketsecurity/lib-stable/fs/find'

import { MAX_UNFOLDED_CODE_LINES } from '../fleet/check/long-doc-sections-are-folded.mts'
import { GROUPS, QUOTA_LABELS } from './gen-api-docs-groups.mts'
import { extractSdkClassMethods } from './sdk-method-extraction.mts'

const rootPackageJsonPath = findUpSync('package.json', {
  cwd: path.dirname(fileURLToPath(import.meta.url)),
})
if (!rootPackageJsonPath) {
  throw new Error('Unable to locate repository root (package.json not found).')
}
const rootPath = path.dirname(rootPackageJsonPath)
const classPath = path.join(rootPath, 'src/socket-sdk-class.mts')
const dataPath = path.join(
  rootPath,
  'data/api-method-quota-and-permissions.json',
)

export interface QuotaData {
  api: Record<string, { quota: number; permissions: string[] }>
}

export interface MethodInfo {
  name: string
  isGenerator: boolean
  signature: string
  summary: string
  operationId: string | undefined
  quota: number | undefined
  permissions: string[]
}

/**
 * Extract public ordinary, async, and generator methods from the SocketSdk
 * class and attach adjacent JSDoc metadata.
 */
export function extractMethods(
  options: { source?: string | undefined; data?: QuotaData | undefined } = {},
): MethodInfo[] {
  const { source = readFileSync(classPath, 'utf8'), data = loadQuotaData() } =
    options
  const methods: MethodInfo[] = []
  const names = new Set<string>()
  for (const method of extractSdkClassMethods(source)) {
    const { name, isGenerator, signature, summary, hadOperationIdNone } = method
    if (names.has(name)) {
      continue
    }
    names.add(name)
    const operationId =
      method.operationId ??
      (!hadOperationIdNone && data.api[name] ? name : undefined)
    const entry = operationId
      ? Object.entries(data.api).find(
          ([key]) => key.toLowerCase() === operationId.toLowerCase(),
        )?.[1]
      : undefined
    methods.push({
      name,
      isGenerator,
      signature,
      summary,
      operationId,
      quota: entry?.quota,
      permissions: entry?.permissions ?? [],
    })
  }
  return methods
}

/**
 * Load and parse the quota data file.
 */
export function loadQuotaData(): QuotaData {
  return JSON.parse(readFileSync(dataPath, 'utf8')) as QuotaData
}

/**
 * Render the full markdown document from extracted methods.
 */
export function renderApiDocs(methods: MethodInfo[]): string {
  const byName = new Map(methods.map(m => [m.name, m]))
  const sections: string[] = []
  sections.push('<!--')
  sections.push('  AUTOGENERATED. Do not edit by hand.')
  sections.push('  Regenerate with: pnpm run docs:api')
  sections.push('  Source: scripts/repo/gen-api-docs.mts')
  sections.push('-->')
  sections.push('')
  sections.push('# API Reference')
  sections.push('')
  sections.push(
    'Every public method on `SocketSdk`, grouped by domain. For the runtime model (result shape, pagination, file uploads, escape hatches), see [SDK Concepts](./concepts.md). For quota planning, see [Quota Management](./quota-management.md).',
  )
  sections.push('')
  sections.push(`There are **${methods.length}** public methods.`)
  sections.push('')
  sections.push('## Contents')
  sections.push('')
  for (let i = 0, { length } = GROUPS; i < length; i += 1) {
    const group = GROUPS[i]!
    const anchor = group.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
    sections.push(`- [${group.title}](#${anchor})`)
  }
  const inGroups = new Set<string>()
  for (let i = 0, { length } = GROUPS; i < length; i += 1) {
    const g = GROUPS[i]!
    const methodNames = g.methods
    for (let j = 0, { length: jlen } = methodNames; j < jlen; j += 1) {
      inGroups.add(methodNames[j]!)
    }
  }
  const otherMethods = methods.filter(m => !inGroups.has(m.name))
  if (otherMethods.length > 0) {
    sections.push('- [Other](#other)')
  }
  sections.push('')

  for (let i = 0, { length } = GROUPS; i < length; i += 1) {
    const group = GROUPS[i]!
    sections.push(`## ${group.title}`)
    sections.push('')
    sections.push(group.description)
    sections.push('')
    const methodNames = group.methods
    for (let j = 0, { length: jlen } = methodNames; j < jlen; j += 1) {
      const m = byName.get(methodNames[j]!)
      if (!m) {
        continue
      }
      sections.push(renderMethod(m))
    }
  }

  if (otherMethods.length > 0) {
    sections.push('## Other')
    sections.push('')
    sections.push(
      'Methods not yet placed into a domain group. Add them to `GROUPS` in `scripts/repo/gen-api-docs.mts`.',
    )
    sections.push('')
    for (let i = 0, { length } = otherMethods; i < length; i += 1) {
      const m = otherMethods[i]!
      sections.push(renderMethod(m))
    }
  }

  return (
    sections
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  )
}

/**
 * Render a single method's reference block.
 */
export function renderMethod(m: MethodInfo): string {
  const sigBlock = '```typescript\n' + m.signature + '\n```'
  const summary = m.summary || '_(no description in source)_'
  const parts: string[] = []
  parts.push(`### \`${m.name}\``)
  parts.push('')
  parts.push(summary)
  parts.push('')
  parts.push(
    sigBlock.split(/\r?\n/).length > MAX_UNFOLDED_CODE_LINES
      ? `<details>\n<summary>Signature</summary>\n\n${sigBlock}\n\n</details>`
      : sigBlock,
  )
  parts.push('')

  const meta: string[] = []
  if (m.quota === undefined) {
    meta.push('**Quota:** _not tracked_')
  } else {
    const label = QUOTA_LABELS[m.quota] ?? `${m.quota} units`
    meta.push(`**Quota:** \`${m.quota}\` (${label})`)
  }
  if (m.operationId) {
    meta.push(`**OpenAPI:** \`${m.operationId}\``)
  }
  if (m.permissions.length > 0) {
    meta.push(
      `**Permissions:** ${m.permissions.map(p => '`' + p + '`').join(', ')}`,
    )
  }
  parts.push(meta.join(' · '))
  parts.push('')

  return parts.join('\n')
}
