/* oxlint-disable socket/no-npx-dlx -- test fixture: asserts on the literal `npx` marker that the hook's bypass detector looks for. */

// node --test specs for .git-hooks/_helpers.mts.
//
// Covers the pure-function surface: AI-attribution scanner, marker
// alias logic, suppression matching, backtick span detection, secret
// scanners (Personal-paths / Linear / GitHub / AWS / Private-keys),
// placeholder + replacement suggestion helpers, and the canonical
// marker emitter. Hook entry points (commit-msg / pre-commit /
// pre-push) have their own .test.mts files that exercise stdin/stdout
// against a temp git repo.

import test from 'node:test'
import assert from 'node:assert/strict'

import {
  aliasMatches,
  containsAiAttribution,
  filterAllowedApiKeys,
  gitOrThrow,
  isInsideBackticks,
  lineIsSuppressed,
  looksLikeDocumentation,
  normalizePath,
  scanAwsKeys,
  scanCrossRepoPaths,
  scanGitHubTokens,
  scanLinearRefs,
  scanPersonalPaths,
  scanPrivateKeys,
  scanSocketApiKeys,
  socketHookMarkerFor,
  splitLines,
  stripAiAttribution,
  suggestLoggerReplacement,
  suggestNpxReplacement,
  suggestPlaceholder,
} from '../_helpers.mts'

// ── containsAiAttribution ─────────────────────────────────────────

test('containsAiAttribution: catches "Generated with Claude"', () => {
  assert.strictEqual(containsAiAttribution('Generated with Claude Code'), true)
  assert.strictEqual(containsAiAttribution('Generated with AI'), true)
})

test('containsAiAttribution: catches "Co-Authored-By:" tags', () => {
  assert.strictEqual(
    containsAiAttribution('Co-Authored-By: Claude <noreply@anthropic.com>'),
    true,
  )
  assert.strictEqual(containsAiAttribution('Co-Authored-By: AI'), true)
})

test('containsAiAttribution: catches alternative attribution verbs', () => {
  for (const verb of [
    'Built',
    'Created',
    'Made',
    'Written',
    'Authored',
    'Powered',
    'Crafted',
  ]) {
    assert.strictEqual(
      containsAiAttribution(`${verb} with Claude`),
      true,
      `${verb} with Claude should match`,
    )
    assert.strictEqual(
      containsAiAttribution(`${verb} by Claude`),
      true,
      `${verb} by Claude should match`,
    )
  }
})

test('containsAiAttribution: catches alternative agent names', () => {
  for (const agent of [
    'Claude',
    'AI',
    'GPT',
    'ChatGPT',
    'Copilot',
    'Cursor',
    'Bard',
    'Gemini',
  ]) {
    assert.strictEqual(
      containsAiAttribution(`Generated by ${agent}`),
      true,
      `Generated by ${agent} should match`,
    )
  }
})

test('containsAiAttribution: catches emoji + email + line-start markers', () => {
  assert.strictEqual(containsAiAttribution('🤖 Generated by foo'), true)
  assert.strictEqual(containsAiAttribution('AI generated'), true)
  assert.strictEqual(containsAiAttribution('AI-generated'), true)
  assert.strictEqual(containsAiAttribution('Machine generated'), true)
  assert.strictEqual(containsAiAttribution('Machine-generated'), true)
  assert.strictEqual(containsAiAttribution('user@anthropic.com'), true)
  assert.strictEqual(containsAiAttribution('user@openai.com'), true)
  assert.strictEqual(containsAiAttribution('Assistant: hello'), true)
  assert.strictEqual(
    containsAiAttribution('line1\nAssistant: hello'),
    true,
    'multi-line: Assistant: at line start',
  )
})

test('containsAiAttribution: ignores legitimate product/prose mentions', () => {
  // The regression that prompted the fix: bare "Claude Code" or
  // "Claude" in prose without an attribution verb must NOT trigger.
  assert.strictEqual(
    containsAiAttribution(
      "Catches the failure mode where CLAUDE.md grows past Claude Code's warning threshold",
    ),
    false,
  )
  assert.strictEqual(
    containsAiAttribution(
      'Adds two PreToolUse hooks that enforce the fleet "Allow X bypass" phrase policy',
    ),
    false,
  )
  assert.strictEqual(
    containsAiAttribution('See .claude/hooks/no-revert-guard for details'),
    false,
  )
  assert.strictEqual(
    containsAiAttribution('the assistant returned an error'),
    false,
    'lowercase "assistant" mid-line should not match',
  )
  assert.strictEqual(
    containsAiAttribution('using the Claude Sonnet 4.6 model'),
    false,
    'model-name reference should not match',
  )
})

// ── stripAiAttribution ────────────────────────────────────────────

test('stripAiAttribution: removes only attribution lines', () => {
  const input = [
    'feat(auth): add login flow',
    '',
    'Implements the OAuth callback handler.',
    '',
    'Co-Authored-By: Claude <noreply@anthropic.com>',
    '🤖 Generated with Claude Code',
  ].join('\n')
  const { cleaned, removed } = stripAiAttribution(input)
  assert.strictEqual(removed, 2)
  assert.match(cleaned, /feat\(auth\): add login flow/)
  assert.match(cleaned, /Implements the OAuth callback handler\./)
  assert.doesNotMatch(cleaned, /Co-Authored-By/)
  assert.doesNotMatch(cleaned, /🤖/)
})

test('stripAiAttribution: keeps prose mentioning Claude in context', () => {
  const input = [
    'fix(hooks): tighten Claude Code marker handling',
    '',
    'See .claude/hooks/ for the canonical hook layout.',
  ].join('\n')
  const { cleaned, removed } = stripAiAttribution(input)
  assert.strictEqual(removed, 0)
  assert.strictEqual(cleaned, input)
})

// ── aliasMatches ──────────────────────────────────────────────────

test('aliasMatches: identity match', () => {
  assert.strictEqual(aliasMatches('console', 'console'), true)
  assert.strictEqual(aliasMatches('npx', 'npx'), true)
})

test('aliasMatches: legacy logger → console alias', () => {
  assert.strictEqual(aliasMatches('logger', 'console'), true)
  assert.strictEqual(aliasMatches('console', 'logger'), true)
})

test('aliasMatches: unrelated names do not match', () => {
  assert.strictEqual(aliasMatches('console', 'npx'), false)
  assert.strictEqual(aliasMatches('foo', 'bar'), false)
})

// ── lineIsSuppressed ──────────────────────────────────────────────

test('lineIsSuppressed: bare marker = blanket allow', () => {
  assert.strictEqual(
    lineIsSuppressed('console.log("x") // socket-hook: allow', 'console'),
    true,
  )
  assert.strictEqual(lineIsSuppressed('foo() // socket-hook: allow'), true)
})

test('lineIsSuppressed: rule-named marker matches the named rule', () => {
  assert.strictEqual(
    lineIsSuppressed(
      'console.log("x") // socket-hook: allow console',
      'console',
    ),
    true,
  )
  assert.strictEqual(
    lineIsSuppressed('console.log("x") // socket-hook: allow npx', 'console'),
    false,
    'npx marker does NOT suppress console rule',
  )
})

test('lineIsSuppressed: alias-named marker also matches', () => {
  // legacy `allow logger` still suppresses the console rule
  assert.strictEqual(
    lineIsSuppressed(
      'console.log("x") // socket-hook: allow logger',
      'console',
    ),
    true,
  )
})

test('lineIsSuppressed: returns false when no marker', () => {
  assert.strictEqual(lineIsSuppressed('console.log("x")', 'console'), false)
})

// ── isInsideBackticks ─────────────────────────────────────────────

test('isInsideBackticks: pattern entirely within span', () => {
  assert.strictEqual(
    isInsideBackticks('use the `npx` command', /\bnpx\b/),
    true,
  )
})

test('isInsideBackticks: pattern only outside span', () => {
  assert.strictEqual(
    isInsideBackticks('npx is `something else`', /\bnpx\b/),
    false,
  )
})

test('isInsideBackticks: no spans → false', () => {
  assert.strictEqual(isInsideBackticks('plain text', /\bnpx\b/), false)
})

// ── looksLikeDocumentation ────────────────────────────────────────

test('looksLikeDocumentation: comment lines pass as docs', () => {
  assert.strictEqual(
    looksLikeDocumentation('// uses npx for the build', /\bnpx\b/),
    true,
  )
  assert.strictEqual(
    looksLikeDocumentation(' * runs npx in CI', /\bnpx\b/),
    true,
  )
  assert.strictEqual(
    looksLikeDocumentation('# npx documentation', /\bnpx\b/),
    true,
  )
})

test('looksLikeDocumentation: JSDoc tag lines pass as docs', () => {
  assert.strictEqual(
    looksLikeDocumentation('@example npx prettier', /\bnpx\b/),
    true,
  )
})

test('looksLikeDocumentation: backtick-only mentions pass', () => {
  assert.strictEqual(
    looksLikeDocumentation('use `npx` instead', /\bnpx\b/),
    true,
  )
})

test('looksLikeDocumentation: bare runtime call does not pass', () => {
  assert.strictEqual(
    looksLikeDocumentation('npx prettier --write', /\bnpx\b/),
    false,
  )
})

// ── normalizePath ─────────────────────────────────────────────────

test('normalizePath: Windows backslashes → forward slashes', () => {
  assert.strictEqual(
    normalizePath('C:\\Users\\jdalton\\project'),
    'C:/Users/jdalton/project',
  )
})

test('normalizePath: POSIX path passes through', () => {
  assert.strictEqual(
    normalizePath('/Users/jdalton/project'),
    '/Users/jdalton/project',
  )
})

// ── filterAllowedApiKeys ──────────────────────────────────────────

test('filterAllowedApiKeys: drops fake-token + env-var-name + .example markers', () => {
  // SOCKET_TOKEN_ENV_NAMES carries the trailing `=` — the filter looks
  // for the assignment shape, not the bare name in prose.
  const lines = [
    'const real = "abc123secretvalueabcdef"',
    'const fake = "socket-test-fake-token-abc"',
    'export SOCKET_API_TOKEN=somevalue',
    'const example = "this is .example fixture data"',
  ]
  const filtered = filterAllowedApiKeys(lines)
  assert.deepStrictEqual(filtered, ['const real = "abc123secretvalueabcdef"'])
})

test('filterAllowedApiKeys: retains lines without allowlist hits', () => {
  const lines = ['line one', 'line two']
  assert.deepStrictEqual(filterAllowedApiKeys(lines), lines)
})

// ── socketHookMarkerFor ───────────────────────────────────────────

test('socketHookMarkerFor: emits canonical comment for .ts', () => {
  const marker = socketHookMarkerFor('src/foo.ts', 'console')
  assert.match(marker, /socket-hook:\s*allow\s+console/)
})

test('socketHookMarkerFor: chooses comment style by file extension', () => {
  const py = socketHookMarkerFor('foo.py', 'npx')
  const yml = socketHookMarkerFor('ci.yml', 'npx')
  assert.match(py, /^#/)
  assert.match(yml, /^#/)
  const ts = socketHookMarkerFor('foo.ts', 'npx')
  assert.match(ts, /^\/\//)
})

// ── suggestPlaceholder ────────────────────────────────────────────

test('suggestPlaceholder: rewrites /Users/<name>/ → /Users/<user>/', () => {
  const out = suggestPlaceholder('const p = "/Users/jdalton/foo.txt"')
  assert.match(out, /\/Users\/<user>\//)
})

test('suggestPlaceholder: rewrites C:\\Users\\<name>\\ → C:\\Users\\<USERNAME>\\', () => {
  // String contains 1 literal backslash per separator: C:\Users\jdalton\Documents
  const out = suggestPlaceholder('const p = "C:\\Users\\jdalton\\Documents"')
  assert.match(out, /C:\\Users\\<USERNAME>\\/)
})

// ── suggestNpxReplacement ─────────────────────────────────────────

test('suggestNpxReplacement: npx → pnpm exec', () => {
  assert.strictEqual(
    suggestNpxReplacement('npx prettier --check'),
    'pnpm exec prettier --check',
  )
})

test('suggestNpxReplacement: pnpm dlx → pnpm exec', () => {
  assert.strictEqual(
    suggestNpxReplacement('pnpm dlx tsx foo.ts'),
    'pnpm exec tsx foo.ts',
  )
})

test('suggestNpxReplacement: yarn dlx → pnpm exec', () => {
  assert.strictEqual(
    suggestNpxReplacement('yarn dlx tsx foo.ts'),
    'pnpm exec tsx foo.ts',
  )
})

test('suggestNpxReplacement: pnx → pnpm exec', () => {
  assert.strictEqual(
    suggestNpxReplacement('pnx tsx foo.ts'),
    'pnpm exec tsx foo.ts',
  )
})

test('suggestNpxReplacement: leaves non-dlx commands alone', () => {
  assert.strictEqual(
    suggestNpxReplacement('pnpm install --frozen-lockfile'),
    'pnpm install --frozen-lockfile',
  )
})

// ── suggestLoggerReplacement ──────────────────────────────────────

test('suggestLoggerReplacement: console.log → logger.log', () => {
  const out = suggestLoggerReplacement("console.log('hi')")
  assert.match(out, /logger\.(log|info)/)
})

test('suggestLoggerReplacement: console.error → logger.fail', () => {
  const out = suggestLoggerReplacement("console.error('x')")
  assert.match(out, /logger\.(fail|error)/)
})

// ── scanPersonalPaths ─────────────────────────────────────────────

test('scanPersonalPaths: flags real /Users/<name>/ paths', () => {
  const hits = scanPersonalPaths('const p = "/Users/jdalton/secret.txt"')
  assert.ok(hits.length > 0)
  assert.match(hits[0]!.line, /jdalton/)
})

test('scanPersonalPaths: ignores placeholder /Users/<user>/', () => {
  const hits = scanPersonalPaths('const p = "/Users/<user>/foo"')
  assert.strictEqual(hits.length, 0)
})

test('scanPersonalPaths: ignores Linux placeholder /home/<user>/', () => {
  const hits = scanPersonalPaths('const p = "/home/<user>/foo"')
  assert.strictEqual(hits.length, 0)
})

test('scanPersonalPaths: respects suppression marker', () => {
  // Canonical rule name is singular: `personal-path`.
  const hits = scanPersonalPaths(
    'const p = "/Users/jdalton/foo" // socket-hook: allow personal-path',
  )
  assert.strictEqual(hits.length, 0)
})

test('scanPersonalPaths: bare-allow marker also suppresses', () => {
  const hits = scanPersonalPaths(
    'const p = "/Users/jdalton/foo" // socket-hook: allow',
  )
  assert.strictEqual(hits.length, 0)
})

// ── scanLinearRefs ────────────────────────────────────────────────

test('scanLinearRefs: catches enumerated team-key IDs', () => {
  // SOC- is NOT in the team-key list; ENG-, INFRA-, OPS- are.
  const hits = scanLinearRefs('Fixes ENG-9999 and INFRA-42 and OPS-7')
  assert.strictEqual(hits.length, 3)
  assert.ok(hits.includes('ENG-9999'))
  assert.ok(hits.includes('INFRA-42'))
  assert.ok(hits.includes('OPS-7'))
})

test('scanLinearRefs: ignores unenumerated 3+ letter prefixes', () => {
  // SOC- and FOO- are not in the team-key list.
  const hits = scanLinearRefs('Tracking SOC-1234 and FOO-99')
  assert.strictEqual(hits.length, 0)
})

test('scanLinearRefs: catches linear.app URLs', () => {
  const hits = scanLinearRefs('See https://linear.app/socket/issue/SOC-1')
  assert.ok(hits.length >= 1)
})

test('scanLinearRefs: respects limit cap', () => {
  const text = Array.from({ length: 20 }, (_, i) => `SOC-${i}`).join(' ')
  const hits = scanLinearRefs(text, 3)
  assert.ok(hits.length <= 3)
})

test('scanLinearRefs: ignores arbitrary 3-letter prefixes (ABC-)', () => {
  const hits = scanLinearRefs('issue ABC-123 was filed')
  assert.strictEqual(hits.length, 0)
})

test('scanLinearRefs: skips lines that start with #', () => {
  // Comment-style lines (commit-message comments) are skipped wholesale.
  const hits = scanLinearRefs('# tracking ENG-1 and ENG-2')
  assert.strictEqual(hits.length, 0)
})

// ── scanGitHubTokens / scanAwsKeys / scanPrivateKeys ─────────────

test('scanGitHubTokens: catches ghp_* literal', () => {
  const hits = scanGitHubTokens(
    'GITHUB_TOKEN=ghp_abcdefghijklmnopqrstuvwxyzABCDEF1234',
  )
  assert.ok(hits.length >= 1)
})

test('scanGitHubTokens: catches ghs_* literal too', () => {
  const hits = scanGitHubTokens(
    'TOKEN=ghs_abcdefghijklmnopqrstuvwxyzABCDEF1234',
  )
  assert.ok(hits.length >= 1)
})

test('scanAwsKeys: catches AKIA literal access key', () => {
  const hits = scanAwsKeys('AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE')
  assert.ok(hits.length >= 1)
})

test('scanPrivateKeys: catches PEM header', () => {
  const hits = scanPrivateKeys('-----BEGIN RSA PRIVATE KEY-----')
  assert.ok(hits.length >= 1)
})

// ── scanSocketApiKeys ─────────────────────────────────────────────

test('scanSocketApiKeys: catches sktsec_ literal', () => {
  // The line MUST NOT contain the env-var-name shape (`SOCKET_API_TOKEN=`)
  // or it gets allowlisted as a documented env-name reference.
  const hits = scanSocketApiKeys('const t = "sktsec_abc123abc123abc123abc123"')
  assert.ok(hits.length >= 1)
})

test('scanSocketApiKeys: ignores allowlisted fake-token shape', () => {
  const hits = scanSocketApiKeys('const t = "socket-test-fake-token-abc"')
  assert.strictEqual(hits.length, 0)
})

test('scanSocketApiKeys: env-var-name shape is allowlisted', () => {
  // The trailing `=` triggers the env-var-name allowlist.
  const hits = scanSocketApiKeys(
    'export SOCKET_API_TOKEN=sktsec_realsecretrealsecret',
  )
  assert.strictEqual(hits.length, 0)
})

// ── scanCrossRepoPaths ────────────────────────────────────────────

test('scanCrossRepoPaths: flags ../<other-repo>/ relative escapes', () => {
  const hits = scanCrossRepoPaths(
    'import x from "../socket-cli/src/foo"',
    'src/test.ts',
  )
  assert.ok(hits.length >= 1)
})

test('scanCrossRepoPaths: flags absolute /Users/.../projects/<other-repo>', () => {
  const hits = scanCrossRepoPaths(
    'const p = "/Users/jdalton/projects/socket-cli/lib/foo"',
    'src/test.ts',
  )
  assert.ok(hits.length >= 1)
})

test('scanCrossRepoPaths: allows same-repo relative imports', () => {
  const hits = scanCrossRepoPaths('import x from "./foo"', 'src/test.ts')
  assert.strictEqual(hits.length, 0)
})

// ── splitLines (CRLF normalization) ───────────────────────────────

test('splitLines: LF-only input passes through', () => {
  assert.deepStrictEqual(splitLines('a\nb\nc'), ['a', 'b', 'c'])
})

test('splitLines: CRLF input normalizes to LF', () => {
  assert.deepStrictEqual(splitLines('a\r\nb\r\nc'), ['a', 'b', 'c'])
})

test('splitLines: mixed CRLF + LF input normalizes', () => {
  assert.deepStrictEqual(splitLines('a\r\nb\nc\r\nd'), ['a', 'b', 'c', 'd'])
})

test('splitLines: trailing CRLF produces a trailing empty', () => {
  assert.deepStrictEqual(splitLines('a\r\n'), ['a', ''])
})

test('splitLines: standalone \\r is preserved (mac classic — out of scope)', () => {
  // Modern git / subprocess output is LF or CRLF, never bare CR. We
  // don't try to normalize CR-only line endings; the helper is a
  // pragmatic CRLF stripper, not a full line-ending sniffer.
  assert.deepStrictEqual(splitLines('a\rb'), ['a\rb'])
})

// ── gitOrThrow ────────────────────────────────────────────────────

test('gitOrThrow: returns stdout on success', () => {
  // `git --version` works in any environment with git on PATH.
  const out = gitOrThrow('--version')
  assert.ok(out.startsWith('git version'), `expected "git version ...", got ${out}`)
})

test('gitOrThrow: throws on non-zero exit', () => {
  assert.throws(
    () => gitOrThrow('this-subcommand-does-not-exist'),
    /git this-subcommand-does-not-exist:/,
  )
})
