// GENERATED by scripts/fleet/make-hook-dispatch.mts — do not edit by hand.
// Snapshot-EXCLUDED hooks only (@dispatch-snapshot-exclude): bundled to
// excluded-bundle.cjs and spliced in by deserialize-main at runtime.
// Re-run the maker after adding/removing an eligible hook, then rebuild
// the bundle with scripts/fleet/build-hook-bundle.mts.

import type { DispatchHookEntry } from './dispatch.mts'

import { hook as hook0 } from '../brew-supply-chain-guard/index.mts'
import { hook as hook1 } from '../check-new-deps/index.mts'

export const DISPATCH_TABLE: Record<string, readonly DispatchHookEntry[]> = {
  __proto__: null,
  'PreToolUse': [
    { name: 'brew-supply-chain-guard', check: hook0.check, tools: ['Bash'] },
    { name: 'check-new-deps', check: hook1.check, tools: ['Edit', 'Write', 'MultiEdit'] },
  ],
} as Record<string, readonly DispatchHookEntry[]>

export const EXCLUDED_HOOK_HINTS: Record<
  string,
  readonly string[] | null
> = {
  __proto__: null,
  'PreToolUse': ['Bash', 'Edit', 'MultiEdit', 'Write'],
} as Record<string, readonly string[] | null>
