#!/usr/bin/env node
/**
 * @file The single-process fleet hook dispatcher. Claude Code can invoke one
 *   `node _dispatch/index.cjs <Event>` per hook event instead of spawning a
 *   separate `node <hook>/index.mts` per hook. The loader (`index.cjs`) turns
 *   on the V8 compile cache, then requires the rolldown CJS bundle whose entry
 *   is THIS module's compiled form.
 *
 *   The dispatcher reads the event arg + stdin ONCE, then runs every bundled
 *   hook registered for that event from the STATIC dispatch table
 *   (`dispatch-table.mts`, generated by `scripts/fleet/make-hook-dispatch.mts`).
 *   A static table is what lets rolldown bundle the hooks: a dynamic
 *   `import(path.join(HOOKS_DIR, rel))` is opaque to the bundler.
 *
 *   Trigger pre-flight + early-exit: a bundled hook entry can declare the tool
 *   names it cares about; the dispatcher skips a hook whose tool doesn't match
 *   before importing/running it, so an unrelated event is a near no-op.
 *
 *   settings.json routes each hook event to this dispatcher, which runs every
 *   bundle-safe hook for the event from the static table. It writes
 *   reminder/notify text to stderr; a blocking hook's verdict sets exit code 2
 *   (PreToolUse / PostToolUse) or emits the stdout-JSON decision protocol
 *   (Stop), via `DispatchResult.decision`.
 */

import process from 'node:process'
import v8 from 'node:v8'

import { readStdin } from '../_shared/transcript.mts'

import { DISPATCH_TABLE } from './dispatch-table.mts'

export interface DispatchPayload {
  readonly cwd?: string | undefined
  readonly hook_event_name?: string | undefined
  readonly tool_input?: Record<string, unknown> | undefined
  readonly tool_name?: string | undefined
  readonly transcript_path?: string | undefined
}

/**
 * A guard verdict the dispatcher understands. Mirrors `_shared/guard.mts`'s
 * `GuardResult` but lives here so the dispatch table can carry `defineHook`
 * hooks (which return a verdict) alongside the legacy pure-`run` hooks (which
 * return a reminder string) WITHOUT the dispatcher importing the guard module.
 * `'block'` sets exitCode 2 + prints `message`; `'notify'` prints `message`
 * (stderr, exit 0); `undefined` is silent allow.
 */
export type DispatchVerdict =
  | { readonly kind: 'block'; readonly message: string }
  | { readonly kind: 'notify'; readonly message: string }
  | undefined

export interface DispatchHookEntry {
  /**
   * The hook leaf name (the `fleet/<name>` dir), for diagnostics.
   */
  readonly name: string
  /**
   * Tool names this hook handles. Empty/omitted means "any tool" (e.g. Stop
   * hooks). The dispatcher uses this for the trigger pre-flight early-exit.
   */
  readonly tools?: readonly string[] | undefined
  /**
   * Legacy pure entry: returns reminder text to surface on stderr, or
   * `undefined`. Mutually exclusive with `check` — exactly one is set per entry.
   * (bundle-stale-reminder style.)
   */
  readonly run?: (payload: DispatchPayload) => string | undefined
  /**
   * `defineHook`-contract entry: returns a verdict (block / notify / allow).
   * The maker wraps each eligible `defineHook` hook's `check` into this seam so
   * the dispatcher can run a blocking guard from the snapshot WITHOUT a dynamic
   * import. `check` may be sync OR async; the dispatcher awaits it.
   */
  readonly check?: ((
    payload: DispatchPayload,
  ) => DispatchVerdict | Promise<DispatchVerdict>) | undefined
}

export interface DispatchResult {
  /**
   * `'block'` when any fired guard returned a block verdict; else `'allow'`.
   */
  readonly decision: 'allow' | 'block'
  /**
   * Reminder / notify / block lines collected from the hooks that fired (in
   * fire order). All are surfaced on stderr by the CLI.
   */
  readonly reminders: readonly string[]
  /**
   * The block reason to surface, when `decision === 'block'`. The CLI prints
   * this on stderr and sets exitCode 2 (PreToolUse / PostToolUse protocol).
   */
  readonly blockReason?: string | undefined
}

/**
 * Returns true when the hook entry handles the payload's tool. An entry with
 * no declared tools handles every event (Stop / SessionStart style).
 */
export function hookHandlesTool(
  entry: DispatchHookEntry,
  toolName: string | undefined,
): boolean {
  if (!entry.tools || entry.tools.length === 0) {
    return true
  }
  if (!toolName) {
    return false
  }
  return entry.tools.includes(toolName)
}

/**
 * Run every bundled hook registered for `event` against `payload`. Pure: no
 * process I/O (it only invokes the hooks' pure `run`/`check` fns), so it is
 * unit-testable and the bundler can tree-shake freely. Async because a
 * `defineHook` `check` may be async; legacy pure-`run` hooks resolve sync.
 *
 * A `block` verdict short-circuits: once a guard blocks, later hooks are
 * skipped (a block is terminal — the tool call is rejected — so there is no
 * point running the rest, and it matches the per-process guard semantics).
 */
export async function dispatch(
  event: string,
  payload: DispatchPayload,
): Promise<DispatchResult> {
  const entries = DISPATCH_TABLE[event] ?? []
  const reminders: string[] = []
  const toolName = payload.tool_name
  let blockReason: string | undefined
  for (let i = 0, { length } = entries; i < length; i += 1) {
    const entry = entries[i]!
    if (!hookHandlesTool(entry, toolName)) {
      continue
    }
    try {
      if (entry.check) {
        const verdict = await entry.check(payload)
        if (verdict) {
          reminders.push(verdict.message)
          if (verdict.kind === 'block') {
            blockReason = verdict.message
            break
          }
        }
      } else if (entry.run) {
        const text = entry.run(payload)
        if (text) {
          reminders.push(text)
        }
      }
    } catch {
      // A misbehaving bundled hook must never wedge the whole dispatcher.
    }
  }
  return {
    __proto__: null,
    decision: blockReason === undefined ? 'allow' : 'block',
    reminders,
    blockReason,
  } as DispatchResult
}

/**
 * The dispatcher CLI: read the event arg (`process.argv[2]`) + stdin once, run
 * the bundled hooks, surface reminders on stderr, exit 0. Exported (not
 * auto-run) so the rolldown bundle entry (`dispatch-entry.mts`) can call it
 * unconditionally while unit tests / the source module stay import-safe — a
 * CJS bundle has no `import.meta`, so an entrypoint-guard can't gate it there.
 */
export async function runDispatcherCli(): Promise<void> {
  const event = process.argv[2]
  if (!event) {
    process.exit(0)
  }
  let raw: string
  try {
    raw = await readStdin()
  } catch {
    process.exit(0)
  }
  if (!raw.trim()) {
    process.exit(0)
  }
  let payload: DispatchPayload
  try {
    payload = JSON.parse(raw) as DispatchPayload
  } catch {
    process.exit(0)
  }
  const result = await dispatch(event, payload)
  if (result.reminders.length) {
    process.stderr.write(result.reminders.join('\n') + '\n')
  }
  // A Stop-event block uses Claude Code's stdout-JSON decision protocol; a
  // PreToolUse / PostToolUse block uses exitCode 2 + the reason on stderr
  // (already written above as a reminder line).
  if (result.decision === 'block' && result.blockReason !== undefined) {
    if (payload.tool_name === undefined) {
      process.stdout.write(
        JSON.stringify({ decision: 'block', reason: result.blockReason }),
      )
      process.exit(0)
    }
    process.exit(2)
  }
  process.exit(0)
}

// Direct `node dispatch.mts <Event>` execution (dev / test harness) runs the
// CLI; importing the module for its pure helpers does not.
//
// The `isBuildingSnapshot()` clause is load-bearing for the snapshot build:
// `dispatch-snapshot-entry.mts` imports `dispatch` from here, so this whole
// module — including this guard — is in the snapshot bundle's top-level eval
// graph. When `node --build-snapshot <bundle.cjs>` is invoked with an ABSOLUTE
// entry path, `process.argv[1]` is that absolute path and rolldown's CJS form of
// `import.meta.url` (`pathToFileURL(__filename).href`) resolves to the SAME
// absolute file URL — so the guard's equality holds, `runDispatcherCli()` fires
// during the BUILD pass, hits empty stdin/argv, and `process.exit(0)`s — which
// silently aborts serialization (exit 0, NO blob, only the `node:module`
// warning). (A RELATIVE entry path masks it: `argv[1]` is bare, the URL is
// absolute, so they don't match.) Gating on `!isBuildingSnapshot()` keeps the
// dev/test self-exec while making the guard inert inside the snapshot builder,
// where the dispatcher must run ONLY from the registered deserialize-main.
if (
  !v8.startupSnapshot.isBuildingSnapshot() &&
  process.argv[1] &&
  import.meta.url === `file://${process.argv[1]}`
) {
  runDispatcherCli().catch(() => {
    process.exit(0)
  })
}
