#!/usr/bin/env node
/**
 * @file The single-process fleet hook dispatcher. Claude Code can invoke one
 *   `node _dispatch/index.cjs <Event>` per hook event instead of spawning a
 *   separate `node <hook>/index.mts` per hook. The loader (`index.cjs`) turns
 *   on the V8 compile cache, then requires the rolldown CJS bundle whose entry
 *   is THIS module's compiled form.
 *
 *   The dispatcher reads the event arg + stdin ONCE, then runs every bundled
 *   hook registered for that event from the STATIC dispatch table
 *   (`dispatch-table.mts`, generated by `scripts/fleet/make-hook-dispatch.mts`).
 *   A static table is what lets rolldown bundle the hooks: a dynamic
 *   `import(path.join(HOOKS_DIR, rel))` is opaque to the bundler.
 *
 *   Trigger pre-flight + early-exit: a bundled hook entry can declare the tool
 *   names it cares about; the dispatcher skips a hook whose tool doesn't match
 *   before importing/running it, so an unrelated event is a near no-op.
 *
 *   settings.json routes each hook event to this dispatcher, which runs every
 *   bundle-safe hook for the event from the static table. It writes
 *   reminder/notify text to stderr; a blocking hook's verdict sets exit code 2
 *   (PreToolUse / PostToolUse) or emits the stdout-JSON decision protocol
 *   (Stop), via `DispatchResult.decision`.
 */

import process from 'node:process'

import { parseCommands } from '../_shared/shell-command.mts'
import { readStdin } from '../_shared/transcript.mts'

import { DISPATCH_TABLE } from './dispatch-table.mts'
import { isHookEntrypoint } from '../_shared/entrypoint.mts'

// State-mutating segment families whose SILENT cancellation strands work. A
// block on one segment of a compound Bash command cancels the whole chain —
// including a `git commit` / `git push` chained before the blocked step — and
// the agent's narrative marks them landed while nothing ran. Incident: a
// sibling-repo test commit + push died as collateral of a blocked
// `gh pr create` at the end of the same chain; the PR shipped without its
// tests until the Stop guard caught the dirty worktree.
const MUTATING_GIT_VERBS: ReadonlySet<string> = new Set([
  'cherry-pick',
  'commit',
  'merge',
  'push',
  'tag',
])

/**
 * The state-changing segments in `command` (deduped, human-readable), so a
 * block verdict can announce what else its cancellation took down.
 */
export function mutatingSegments(command: string): string[] {
  const found: string[] = []
  for (const c of parseCommands(command)) {
    const verbs = c.args.filter(a => !a.startsWith('-'))
    const verb = verbs[0] ?? ''
    if (c.binary === 'git' && MUTATING_GIT_VERBS.has(verb)) {
      found.push(`git ${verb}`)
    } else if (c.binary === 'gh' && verb === 'release') {
      found.push(`gh release ${verbs[1] ?? ''}`.trim())
    } else if (
      (c.binary === 'npm' || c.binary === 'pnpm' || c.binary === 'yarn') &&
      verb === 'publish'
    ) {
      found.push(`${c.binary} publish`)
    }
  }
  return [...new Set(found)]
}

/**
 * When a block fires on a compound Bash command that also carries
 * state-changing segments, the addendum makes the collateral cancellation
 * LOUD: those segments did not run and must be re-run separately, FIRST.
 * Returns undefined for single-segment commands or chains with no
 * state-changing segments.
 */
export function cancelledChainAddendum(
  payload: DispatchPayload,
): string | undefined {
  if (payload.tool_name !== 'Bash') {
    return undefined
  }
  const command = payload.tool_input?.['command']
  if (typeof command !== 'string' || !command) {
    return undefined
  }
  if (parseCommands(command).length < 2) {
    return undefined
  }
  const cancelled = mutatingSegments(command)
  if (!cancelled.length) {
    return undefined
  }
  return [
    '',
    '⚠ PRIORITY: this block cancelled the ENTIRE command chain. These',
    '  state-changing steps did NOT run:',
    ...cancelled.map(s => `    • ${s}`),
    '  Re-run them separately FIRST (verify each landed), then retry the',
    '  blocked step on its own. Never assume a chained commit/push survived',
    '  a block.',
  ].join('\n')
}

export interface DispatchPayload {
  readonly cwd?: string | undefined
  readonly hook_event_name?: string | undefined
  readonly tool_input?: Record<string, unknown> | undefined
  readonly tool_name?: string | undefined
  readonly transcript_path?: string | undefined
}

/**
 * A guard verdict the dispatcher understands. Mirrors `_shared/guard.mts`'s
 * `GuardResult` but lives here so the dispatch table can carry `defineHook`
 * hooks (which return a verdict) alongside the legacy pure-`run` hooks (which
 * return a reminder string) WITHOUT the dispatcher importing the guard module.
 * `'block'` sets exitCode 2 + prints `message`; `'notify'` prints `message`
 * (stderr, exit 0); `undefined` is silent allow.
 */
export type DispatchVerdict =
  | { readonly kind: 'block'; readonly message: string }
  | { readonly kind: 'notify'; readonly message: string }
  | undefined

export interface DispatchHookEntry {
  /**
   * The hook leaf name (the `fleet/<name>` dir), for diagnostics.
   */
  readonly name: string
  /**
   * Tool names this hook handles. Empty/omitted means "any tool" (e.g. Stop
   * hooks). The dispatcher uses this for the trigger pre-flight early-exit.
   */
  readonly tools?: readonly string[] | undefined
  /**
   * Legacy pure entry: returns reminder text to surface on stderr, or
   * `undefined`. Mutually exclusive with `check` — exactly one is set per entry.
   * (bundle-stale-reminder style.)
   */
  readonly run?: (payload: DispatchPayload) => string | undefined
  /**
   * `defineHook`-contract entry: returns a verdict (block / notify / allow).
   * The maker wraps each eligible `defineHook` hook's `check` into this seam so
   * the dispatcher can run a blocking guard from the snapshot WITHOUT a dynamic
   * import. `check` may be sync OR async; the dispatcher awaits it.
   */
  readonly check?: ((
    payload: DispatchPayload,
  ) => DispatchVerdict | Promise<DispatchVerdict>) | undefined
}

export interface DispatchResult {
  /**
   * `'block'` when any fired guard returned a block verdict; else `'allow'`.
   */
  readonly decision: 'allow' | 'block'
  /**
   * Reminder / notify / block lines collected from the hooks that fired (in
   * fire order). All are surfaced on stderr by the CLI.
   */
  readonly reminders: readonly string[]
  /**
   * The block reason to surface, when `decision === 'block'`. The CLI prints
   * this on stderr and sets exitCode 2 (PreToolUse / PostToolUse protocol).
   */
  readonly blockReason?: string | undefined
}

/**
 * Returns true when the hook entry handles the payload's tool. An entry with
 * no declared tools handles every event (Stop / SessionStart style).
 */
export function hookHandlesTool(
  entry: DispatchHookEntry,
  toolName: string | undefined,
): boolean {
  if (!entry.tools || entry.tools.length === 0) {
    return true
  }
  if (!toolName) {
    return false
  }
  return entry.tools.includes(toolName)
}

/**
 * Run every bundled hook registered for `event` against `payload`. Pure: no
 * process I/O (it only invokes the hooks' pure `run`/`check` fns), so it is
 * unit-testable and the bundler can tree-shake freely. Async because a
 * `defineHook` `check` may be async; legacy pure-`run` hooks resolve sync.
 *
 * A `block` verdict short-circuits: once a guard blocks, later hooks are
 * skipped (a block is terminal — the tool call is rejected — so there is no
 * point running the rest, and it matches the per-process guard semantics).
 */
export async function dispatch(
  event: string,
  payload: DispatchPayload,
): Promise<DispatchResult> {
  const entries = DISPATCH_TABLE[event] ?? []
  const reminders: string[] = []
  const toolName = payload.tool_name
  let blockReason: string | undefined
  for (let i = 0, { length } = entries; i < length; i += 1) {
    const entry = entries[i]!
    if (!hookHandlesTool(entry, toolName)) {
      continue
    }
    try {
      if (entry.check) {
        const verdict = await entry.check(payload)
        if (verdict) {
          if (verdict.kind === 'block') {
            const addendum = cancelledChainAddendum(payload)
            blockReason =
              addendum === undefined
                ? verdict.message
                : `${verdict.message}\n${addendum}`
            reminders.push(blockReason)
            break
          }
          reminders.push(verdict.message)
        }
      } else if (entry.run) {
        const text = entry.run(payload)
        if (text) {
          reminders.push(text)
        }
      }
    } catch {
      // A misbehaving bundled hook must never wedge the whole dispatcher.
    }
  }
  return {
    __proto__: null,
    decision: blockReason === undefined ? 'allow' : 'block',
    reminders,
    blockReason,
  } as DispatchResult
}

/**
 * The dispatcher CLI: read the event arg (`process.argv[2]`) + stdin once, run
 * the bundled hooks, surface reminders on stderr, exit 0. Exported (not
 * auto-run) so the rolldown bundle entry (`dispatch-entry.mts`) can call it
 * unconditionally while unit tests / the source module stay import-safe — a
 * CJS bundle has no `import.meta`, so an entrypoint-guard can't gate it there.
 */
export async function runDispatcherCli(): Promise<void> {
  const event = process.argv[2]
  if (!event) {
    process.exit(0)
  }
  let raw: string
  try {
    raw = await readStdin()
  } catch {
    process.exit(0)
  }
  if (!raw.trim()) {
    process.exit(0)
  }
  let payload: DispatchPayload
  try {
    payload = JSON.parse(raw) as DispatchPayload
  } catch {
    process.exit(0)
  }
  const result = await dispatch(event, payload)
  if (result.reminders.length) {
    process.stderr.write(result.reminders.join('\n') + '\n')
  }
  // A Stop-event block uses Claude Code's stdout-JSON decision protocol; a
  // PreToolUse / PostToolUse block uses exitCode 2 + the reason on stderr
  // (already written above as a reminder line).
  if (result.decision === 'block' && result.blockReason !== undefined) {
    if (payload.tool_name === undefined) {
      process.stdout.write(
        JSON.stringify({ decision: 'block', reason: result.blockReason }),
      )
      process.exit(0)
    }
    process.exit(2)
  }
  process.exit(0)
}

// Direct `node dispatch.mts <Event>` execution (dev / test harness) runs the
// CLI; importing the module for its pure helpers does not. The snapshot-build
// short circuit is load-bearing: `dispatch-snapshot-entry.mts` imports
// `dispatch` from here, so this whole module — including this guard — is in
// the snapshot bundle's top-level eval graph, and the dispatcher must run ONLY
// from the registered deserialize-main. `isHookEntrypoint` owns that gating
// (plus the realpath comparison); the hazard detail lives in
// `../_shared/entrypoint.mts`.
if (isHookEntrypoint(import.meta.url)) {
  runDispatcherCli().catch(() => {
    process.exit(0)
  })
}
