import { test } from 'node:test'
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const HOOK_PATH = path.join(__dirname, '..', 'index.mts')

function makeTranscript(assistantText: string): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'commit-pr-'))
  const transcriptPath = path.join(dir, 'session.jsonl')
  writeFileSync(
    transcriptPath,
    JSON.stringify({ role: 'user', content: 'do it' }) +
      '\n' +
      JSON.stringify({ role: 'assistant', content: assistantText }),
  )
  return transcriptPath
}

function runHook(transcriptPath: string): { stderr: string; exitCode: number } {
  const result = spawnSync('node', [HOOK_PATH], {
    input: JSON.stringify({ transcript_path: transcriptPath }),
    encoding: 'utf8',
  })
  return { stderr: result.stderr, exitCode: result.status ?? -1 }
}

test('FLAGS "Generated with Claude"', () => {
  const t = makeTranscript('Commit body:\n\nGenerated with Claude Code')
  const { stderr, exitCode } = runHook(t)
  assert.equal(exitCode, 0)
  assert.match(stderr, /commit-pr-reminder/)
  assert.match(stderr, /generated with claude/i)
})

test('FLAGS "Co-Authored-By: Claude"', () => {
  const t = makeTranscript('Trailer:\nCo-Authored-By: Claude <noreply@anthropic.com>')
  const { stderr, exitCode } = runHook(t)
  assert.equal(exitCode, 0)
  assert.match(stderr, /co-authored-by/i)
})

test('FLAGS robot emoji generated tag', () => {
  const t = makeTranscript('PR body:\n🤖 Generated with assistance')
  const { stderr, exitCode } = runHook(t)
  assert.equal(exitCode, 0)
  assert.match(stderr, /robot emoji/i)
})

test('does NOT fire on plain Conventional Commit text', () => {
  const t = makeTranscript('feat(api): add new endpoint\n\nDetails about the change.')
  const { stderr, exitCode } = runHook(t)
  assert.equal(exitCode, 0)
  assert.equal(stderr, '')
})

test('does NOT fire on the word "generated" without "claude" nearby', () => {
  const t = makeTranscript('The build artifacts are generated by tsc.')
  const { stderr, exitCode } = runHook(t)
  assert.equal(exitCode, 0)
  assert.equal(stderr, '')
})

test('disabled env var short-circuits', () => {
  const t = makeTranscript('Generated with Claude Code')
  const result = spawnSync('node', [HOOK_PATH], {
    input: JSON.stringify({ transcript_path: t }),
    encoding: 'utf8',
    env: { ...process.env, SOCKET_COMMIT_PR_REMINDER_DISABLED: '1' },
  })
  assert.equal(result.status, 0)
  assert.equal(result.stderr, '')
})
