// node --test specs for the shared Conventional Commits header validator in
// commit-format.mts — the DRY source for both the commit-message-format-guard
// PreToolUse hook and the commit-msg git-stage backstop.

import assert from 'node:assert/strict'
import { test } from 'node:test'

import {
  ALLOWED_TYPES,
  isAutoGeneratedSubject,
  suggestReplacement,
  validateHeader,
} from '../commit-format.mts'

// ── validateHeader ──────────────────────────────────────────────

test('header: accepts a plain type + description', () => {
  assert.equal(validateHeader('feat: add OAuth callback handler').kind, 'ok')
})

test('header: accepts a scope + breaking-change marker', () => {
  assert.equal(validateHeader('fix(scan)!: drop legacy field').kind, 'ok')
})

test('header: every allowed type passes', () => {
  for (const type of ALLOWED_TYPES) {
    assert.equal(validateHeader(`${type}: do a thing`).kind, 'ok', type)
  }
})

test('header: flags a missing type prefix as no-type', () => {
  assert.equal(validateHeader('just some prose').kind, 'no-type')
})

test('header: flags an unknown type as bad-type', () => {
  const check = validateHeader('wibble: do a thing')
  assert.equal(check.kind, 'bad-type')
  assert.equal(check.kind === 'bad-type' ? check.type : '', 'wibble')
})

test('header: flags an uppercase type', () => {
  const check = validateHeader('Feat: do a thing')
  assert.equal(check.kind, 'uppercase-type')
})

test('header: flags a missing space after the colon as no-type', () => {
  // `feat:description` matches loosely but fails the strict `: ` separator.
  assert.equal(validateHeader('feat:no space').kind, 'no-type')
})

test('header: flags an empty description', () => {
  assert.equal(validateHeader('feat: ').kind, 'empty-description')
})

// ── isAutoGeneratedSubject ──────────────────────────────────────

test('auto: exempts a merge subject', () => {
  assert.equal(isAutoGeneratedSubject("Merge branch 'main' into feature"), true)
})

test('auto: exempts a pull-request merge subject', () => {
  assert.equal(isAutoGeneratedSubject('Merge pull request #12 from x/y'), true)
})

test('auto: exempts a revert subject', () => {
  assert.equal(isAutoGeneratedSubject('Revert "feat: add thing"'), true)
})

test('auto: exempts fixup! / squash! / amend! autosquash subjects', () => {
  assert.equal(isAutoGeneratedSubject('fixup! feat: add thing'), true)
  assert.equal(isAutoGeneratedSubject('squash! feat: add thing'), true)
  assert.equal(isAutoGeneratedSubject('amend! feat: add thing'), true)
})

test('auto: a normal Conventional subject is NOT auto-generated', () => {
  assert.equal(isAutoGeneratedSubject('feat: add thing'), false)
})

test('auto: does not over-match a real word like "Mergeable"', () => {
  // The \\b after Merge keeps `Merged…`/`Mergeable…` from matching as merges.
  assert.equal(isAutoGeneratedSubject('Mergeable state reached'), false)
})

// ── suggestReplacement ──────────────────────────────────────────

test('suggest: ok header yields an empty suggestion', () => {
  assert.equal(suggestReplacement(validateHeader('feat: x')), '')
})

test('suggest: lowercases an uppercase type', () => {
  assert.equal(
    suggestReplacement(validateHeader('Feat: add thing')),
    'feat: add thing',
  )
})

test('suggest: folds a bare-prose subject into a feat header', () => {
  // first word looks like a noun → used as scope.
  assert.equal(
    suggestReplacement(validateHeader('parser handle empty input')),
    'feat(parser): handle empty input',
  )
})
