/**
 * @file Soak-aware Rust/Cargo update runner for the fleet. Rust supply-chain
 *   soak is NATIVE now: cargo nightly ships `-Zmin-publish-age` under RFC 3923.
 *   This runner DRIVES cargo — it is not a hand-rolled crates.io resolver. The
 *   flag only ENABLES the feature; the actual soak threshold is a separate
 *   registry config key (a duration string), and the resolver must be told to
 *   DENY too-new versions or the age is advisory only. Modes: node
 *   scripts/fleet/update/cargo.mts --soak-days 7 Dry plan (default): print the
 *   cargo command + soak config it WOULD run for each own Cargo.toml root. Runs
 *   no cargo. node scripts/fleet/update/cargo.mts --soak-days 7 --apply Apply:
 *   run `cargo update` per root through the fleet lib spawn, handing cargo a
 *   temp config file that enables the min-publish-age soak gate. The soak
 *   window (`--soak-days`) is a TRUST GATE and a REQUIRED param from the
 *   orchestrator — never hardcoded. The only pinned constant is the updater's
 *   nightly toolchain, which gates the tooling, not a crate build.
 */
import { mkdtempSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import process from 'node:process'

import { getDefaultLogger } from '@socketsecurity/lib-stable/logger/default'
import { spawn } from '@socketsecurity/lib-stable/process/spawn/child'

import { findOwnFiles } from './_shared.mts'
import { isMainModule } from '../_shared/is-main-module.mts'

const logger = getDefaultLogger()

/**
 * The nightly toolchain the updater tooling runs on — pinned because
 * `-Zmin-publish-age` is a nightly-only unstable flag. This gates the UPDATER
 * only; it is never a crate build toolchain.
 */
export const RUST_UPDATER_TOOLCHAIN = 'nightly-2026-07-10'

/**
 * The registry config key that carries the soak threshold. The
 * `-Zmin-publish-age` flag (equivalently `[unstable] min-publish-age = true`)
 * enables the feature, but the age itself is set HERE, as a duration string
 * ("<int> <unit>", unit in seconds|minutes|hours|days|weeks|months).
 * Source: RFC 3923 (cargo-min-publish-age).
 */
export const MIN_PUBLISH_AGE_CONFIG_KEY = 'registry.global-min-publish-age'

/**
 * The resolver config key that turns the soak age into a HARD gate: with
 * `"deny"`, cargo ignores any version newer than the soak window unless it is
 * already pinned in Cargo.lock. Without it, the age is advisory only.
 * Source: RFC 3923 (resolver.incompatible-publish-age).
 */
export const INCOMPATIBLE_PUBLISH_AGE_CONFIG_KEY =
  'resolver.incompatible-publish-age'

export interface CargoUpdateArgsOptions {
  readonly precise?: string | undefined
  readonly soakDays: number
  readonly toolchain: string
  readonly workspace?: boolean | undefined
}

export interface CargoUpdate {
  readonly from: string
  readonly name: string
  readonly to: string
}

/**
 * The soak window must be a positive whole number of days — it is the trust
 * gate, so a zero/negative/fractional value is a hard error, never a silent
 * default.
 */
export function assertPositiveSoakDays(soakDays: number): void {
  if (!Number.isInteger(soakDays) || soakDays < 1) {
    throw new Error(
      'Invalid soak window for cargo min-publish-age. ' +
        'Where: scripts/fleet/update/cargo.mts. ' +
        `Saw: ${soakDays}; wanted a positive integer day count (>= 1). ` +
        'Fix: pass --soak-days <N> from the orchestrator.',
    )
  }
}

/**
 * Build the `cargo update` argv that enables the min-publish-age soak gate.
 * Pure — the main test target. The `soakDays` value lands in the config file,
 * not the argv; it is validated here so a bad trust-gate value fails before
 * any spawn.
 */
export function buildCargoUpdateArgs(
  options: CargoUpdateArgsOptions,
): string[] {
  const { precise, soakDays, toolchain, workspace } = options
  assertPositiveSoakDays(soakDays)
  if (!toolchain) {
    throw new Error(
      'Missing cargo toolchain. ' +
        'Where: buildCargoUpdateArgs. ' +
        'Saw: empty toolchain; wanted a `+<toolchain>` name. ' +
        `Fix: pass toolchain: RUST_UPDATER_TOOLCHAIN ('${RUST_UPDATER_TOOLCHAIN}').`,
    )
  }
  const args = [`+${toolchain}`, 'update', '-Zmin-publish-age']
  if (workspace) {
    args.push('--workspace')
  }
  if (precise) {
    args.push('--precise', precise)
  }
  return args
}

/**
 * Render the `.cargo/config.toml` snippet that enables the min-publish-age
 * feature and sets the soak threshold to `soakDays` days. Emits all three
 * pieces the gate needs: the unstable enable flag, the age threshold, and the
 * resolver deny that makes the age binding.
 * Source: RFC 3923 (cargo-min-publish-age).
 */
export function renderMinPublishAgeConfig(soakDays: number): string {
  assertPositiveSoakDays(soakDays)
  return `${[
    '# Generated by scripts/fleet/update/cargo.mts — cargo min-publish-age soak gate.',
    '# Enable the unstable feature (equivalent to the -Zmin-publish-age flag).',
    '[unstable]',
    'min-publish-age = true',
    '',
    '# Soak threshold: reject any registry version whose publish time is newer',
    '# than this window. Duration is "<int> <unit>"',
    '# (seconds|minutes|hours|days|weeks|months).',
    '# Source: RFC 3923 (registry.global-min-publish-age).',
    '[registry]',
    `global-min-publish-age = "${soakDays} days"`,
    '',
    '# Make the age a HARD gate: the resolver ignores too-new versions unless',
    '# they are already pinned in Cargo.lock.',
    '# Source: RFC 3923 (resolver.incompatible-publish-age).',
    '[resolver]',
    'incompatible-publish-age = "deny"',
  ].join('\n')}\n`
}

/**
 * Find first-party workspace Cargo.toml files under `root`, excluding vendored,
 * package-manager, and build directories (see `findOwnFiles`). Returns
 * ASCII-sorted, unix-normalized absolute paths.
 */
export function findOwnCargoManifests(root: string): string[] {
  return findOwnFiles(root, name => name === 'Cargo.toml')
}

/**
 * Parse cargo update's "Updating <name> v<from> -> v<to>" lines into structured
 * records. Cargo prints these status lines to stderr; pass whichever stream
 * carries them (or both joined). Non-matching lines (Adding/Removing/etc.) are
 * ignored.
 */
export function parseCargoUpdateOutput(stdout: string): CargoUpdate[] {
  const updates: CargoUpdate[] = []
  const lines = stdout.split('\n')
  for (let i = 0, { length } = lines; i < length; i += 1) {
    const match = /^\s*Updating\s+(\S+)\s+v(\S+)\s+->\s+v(\S+)/.exec(lines[i]!)
    if (match) {
      updates.push({ from: match[2]!, name: match[1]!, to: match[3]! })
    }
  }
  return updates
}

interface CargoUpdateCliOptions {
  readonly apply: boolean
  readonly precise: string | undefined
  readonly soakDays: number | undefined
  readonly workspace: boolean
}

function parseCliArgs(argv: readonly string[]): CargoUpdateCliOptions {
  let apply = false
  let precise: string | undefined
  let soakDays: number | undefined
  let workspace = false
  for (let i = 0, { length } = argv; i < length; i += 1) {
    const arg = argv[i]!
    if (arg === '--apply') {
      apply = true
    } else if (arg === '--workspace') {
      workspace = true
    } else if (arg === '--soak-days') {
      soakDays = Number(argv[i + 1])
      i += 1
    } else if (arg.startsWith('--soak-days=')) {
      soakDays = Number(arg.slice('--soak-days='.length))
    } else if (arg === '--precise') {
      precise = argv[i + 1]
      i += 1
    } else if (arg.startsWith('--precise=')) {
      precise = arg.slice('--precise='.length)
    }
  }
  return { apply, precise, soakDays, workspace }
}

async function runCargoUpdate(
  args: string[],
  configPath: string,
  manifest: string,
): Promise<string> {
  const fullArgs = [
    ...args,
    '--config',
    configPath,
    '--manifest-path',
    manifest,
  ]
  try {
    const result = await spawn('cargo', fullArgs, {
      stdio: ['inherit', 'pipe', 'pipe'],
      stdioString: true,
    })
    process.stdout.write(String(result.stdout ?? ''))
    process.stderr.write(String(result.stderr ?? ''))
    return `${result.stdout ?? ''}\n${result.stderr ?? ''}`
  } catch (e) {
    const err = e as {
      code?: number | undefined
      stderr?: string | undefined
      stdout?: string | undefined
    }
    process.stdout.write(String(err.stdout ?? ''))
    process.stderr.write(String(err.stderr ?? ''))
    process.exitCode = err.code ?? 1
    return `${err.stdout ?? ''}\n${err.stderr ?? ''}`
  }
}

async function main(): Promise<void> {
  const root = process.cwd()
  const { apply, precise, soakDays, workspace } = parseCliArgs(
    process.argv.slice(2),
  )
  const manifests = findOwnCargoManifests(root)
  if (!manifests.length) {
    logger.info('update/cargo: no first-party Cargo.toml found; nothing to do.')
    return
  }
  if (soakDays === undefined || Number.isNaN(soakDays)) {
    logger.fail(
      'update/cargo: missing soak window. ' +
        'Where: scripts/fleet/update/cargo.mts. ' +
        'Saw: no --soak-days; wanted a positive integer day count. ' +
        'Fix: pass --soak-days <N> from the orchestrator.',
    )
    process.exitCode = 1
    return
  }
  assertPositiveSoakDays(soakDays)

  if (!apply) {
    logger.info(
      `update/cargo: dry plan (soak ${soakDays}d, toolchain ${RUST_UPDATER_TOOLCHAIN}). ` +
        'Re-run with --apply to execute.',
    )
    for (let i = 0, { length } = manifests; i < length; i += 1) {
      const manifest = manifests[i]!
      const args = buildCargoUpdateArgs({
        precise,
        soakDays,
        toolchain: RUST_UPDATER_TOOLCHAIN,
        workspace,
      })
      logger.info(
        `  cargo ${args.join(' ')} --config <temp> --manifest-path ${path.relative(root, manifest)}`,
      )
    }
    logger.info('update/cargo: soak config that would be written:')
    logger.info(renderMinPublishAgeConfig(soakDays))
    return
  }

  const tmpDir = mkdtempSync(path.join(os.tmpdir(), 'fleet-cargo-soak-'))
  const configPath = path.join(tmpDir, 'config.toml')
  writeFileSync(configPath, renderMinPublishAgeConfig(soakDays), 'utf8')
  for (let i = 0, { length } = manifests; i < length; i += 1) {
    const manifest = manifests[i]!
    const args = buildCargoUpdateArgs({
      precise,
      soakDays,
      toolchain: RUST_UPDATER_TOOLCHAIN,
      workspace,
    })
    logger.info(
      `update/cargo: cargo update (${path.relative(root, manifest)}, soak ${soakDays}d)`,
    )
    const output = await runCargoUpdate(args, configPath, manifest)
    const updates = parseCargoUpdateOutput(output)
    logger.info(
      `update/cargo: ${updates.length} crate(s) updated in ${path.relative(root, manifest)}.`,
    )
  }
}

if (isMainModule(import.meta.url)) {
  main().catch((e: unknown) => {
    logger.error(e)
    process.exitCode = 1
  })
}
