/**
 * @fileoverview Configuration constants and enums for the Socket SDK.
 * Provides default values, HTTP agents, and public policy configurations for API interactions.
 */

import rootPkgJson from '../package.json' with { type: 'json' }
import { createUserAgentFromPkgJson } from './user-agent'

import type { ALERT_ACTION, ALERT_TYPE } from './types'

export const DEFAULT_USER_AGENT = createUserAgentFromPkgJson(rootPkgJson)

// https://github.com/sindresorhus/got/blob/v14.4.6/documentation/2-options.md#agent
// Valid HTTP agent names for Got-style agent configuration compatibility.
export const httpAgentNames = new Set(['http', 'https', 'http2'])

// Public security policy.
export const publicPolicy = new Map<ALERT_TYPE, ALERT_ACTION>([
  // error (1):
  ['malware', 'error'],
  // warn (7):
  ['criticalCVE', 'warn'],
  ['didYouMean', 'warn'],
  ['gitDependency', 'warn'],
  ['httpDependency', 'warn'],
  ['licenseSpdxDisj', 'warn'],
  ['obfuscatedFile', 'warn'],
  ['troll', 'warn'],
  // monitor (7):
  ['deprecated', 'monitor'],
  ['mediumCVE', 'monitor'],
  ['mildCVE', 'monitor'],
  ['shrinkwrap', 'monitor'],
  ['telemetry', 'monitor'],
  ['unpopularPackage', 'monitor'],
  ['unstableOwnership', 'monitor'],
  // ignore (85):
  ['ambiguousClassifier', 'ignore'],
  ['badEncoding', 'ignore'],
  ['badSemver', 'ignore'],
  ['badSemverDependency', 'ignore'],
  ['bidi', 'ignore'],
  ['binScriptConfusion', 'ignore'],
  ['chromeContentScript', 'ignore'],
  ['chromeHostPermission', 'ignore'],
  ['chromePermission', 'ignore'],
  ['chromeWildcardHostPermission', 'ignore'],
  ['chronoAnomaly', 'ignore'],
  ['compromisedSSHKey', 'ignore'],
  ['copyleftLicense', 'ignore'],
  ['cve', 'ignore'],
  ['debugAccess', 'ignore'],
  ['deprecatedLicense', 'ignore'],
  ['deprecatedException', 'ignore'],
  ['dynamicRequire', 'ignore'],
  ['emptyPackage', 'ignore'],
  ['envVars', 'ignore'],
  ['explicitlyUnlicensedItem', 'ignore'],
  ['extraneousDependency', 'ignore'],
  ['fileDependency', 'ignore'],
  ['filesystemAccess', 'ignore'],
  ['floatingDependency', 'ignore'],
  ['gitHubDependency', 'ignore'],
  ['gptAnomaly', 'ignore'],
  ['gptDidYouMean', 'ignore'],
  ['gptMalware', 'ignore'],
  ['gptSecurity', 'ignore'],
  ['hasNativeCode', 'ignore'],
  ['highEntropyStrings', 'ignore'],
  ['homoglyphs', 'ignore'],
  ['installScripts', 'ignore'],
  ['invalidPackageJSON', 'ignore'],
  ['invisibleChars', 'ignore'],
  ['licenseChange', 'ignore'],
  ['licenseException', 'ignore'],
  ['longStrings', 'ignore'],
  ['majorRefactor', 'ignore'],
  ['manifestConfusion', 'ignore'],
  ['minifiedFile', 'ignore'],
  ['miscLicenseIssues', 'ignore'],
  ['missingAuthor', 'ignore'],
  ['missingDependency', 'ignore'],
  ['missingLicense', 'ignore'],
  ['missingTarball', 'ignore'],
  ['mixedLicense', 'ignore'],
  ['modifiedException', 'ignore'],
  ['modifiedLicense', 'ignore'],
  ['networkAccess', 'ignore'],
  ['newAuthor', 'ignore'],
  ['noAuthorData', 'ignore'],
  ['noBugTracker', 'ignore'],
  ['noLicenseFound', 'ignore'],
  ['noREADME', 'ignore'],
  ['noRepository', 'ignore'],
  ['noTests', 'ignore'],
  ['noV1', 'ignore'],
  ['noWebsite', 'ignore'],
  ['nonOSILicense', 'ignore'],
  ['nonSPDXLicense', 'ignore'],
  ['nonpermissiveLicense', 'ignore'],
  ['notice', 'ignore'],
  ['obfuscatedRequire', 'ignore'],
  ['peerDependency', 'ignore'],
  ['potentialVulnerability', 'ignore'],
  ['semverAnomaly', 'ignore'],
  ['shellAccess', 'ignore'],
  ['shellScriptOverride', 'ignore'],
  ['socketUpgradeAvailable', 'ignore'],
  ['suspiciousStarActivity', 'ignore'],
  ['suspiciousString', 'ignore'],
  ['trivialPackage', 'ignore'],
  ['typeModuleCompatibility', 'ignore'],
  ['uncaughtOptionalDependency', 'ignore'],
  ['unclearLicense', 'ignore'],
  ['unidentifiedLicense', 'ignore'],
  ['unmaintained', 'ignore'],
  ['unpublished', 'ignore'],
  ['unresolvedRequire', 'ignore'],
  ['unsafeCopyright', 'ignore'],
  ['unusedDependency', 'ignore'],
  ['urlStrings', 'ignore'],
  ['usesEval', 'ignore'],
  ['zeroWidth', 'ignore'],
])
