name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: 'Tests'
    uses: SocketDev/workflows/.github/workflows/reusable-base.yml@master
    with:
      no-lockfile: true
      npm-test-script: 'test-ci'
      node-versions: '18,20,22,24'
      os: 'ubuntu-latest,windows-latest'
