name: Tests

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/_reusable-test.yml
    with:
      setup-script: 'pnpm run build'
      node-versions: '[20, 22, 24]'
      os-versions: '["ubuntu-latest", "windows-latest"]'
      test-script: 'pnpm run test-ci'
      timeout-minutes: 10
      upload-artifacts: false
