name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linting:
    name: "Linting"
    uses: SocketDev/workflows/.github/workflows/reusable-base.yml@master
    with:
      npm-test-script: 'check'
  test:
    name: "Tests"
    uses: SocketDev/workflows/.github/workflows/reusable-base.yml@master
    with:
      npm-test-script: 'test-ci'
      node-versions: '18,20,22,23'
