name: Tests

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: SocketDev/socket-registry/.github/workflows/test.yml@main
