name: Type Checks

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  type-check:
    uses: SocketDev/workflows/.github/workflows/type-check.yml@master
    with:
      no-lockfile: true
      ts-versions: '5.8'
      ts-libs: 'esnext'
