name: Type Checks

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  type-check:
    uses: SocketDev/socket-registry/.github/workflows/types.yml@main
    with:
      setup-script: 'pnpm run build'
