/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketSupplyChainScoreComponents } from './SocketSupplyChainScoreComponents';
import { HttpFile } from '../http/http';

export class SocketSupplyChainScore {
    'score': number;
    'components': SocketSupplyChainScoreComponents;
    'limit'?: number;
    'limitingMetric'?: SocketSupplyChainScoreLimitingMetricEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "SocketSupplyChainScoreComponents",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "limitingMetric",
            "baseName": "limitingMetric",
            "type": "SocketSupplyChainScoreLimitingMetricEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketSupplyChainScore.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketSupplyChainScoreLimitingMetricEnum = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

