/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketCategory } from './SocketCategory';
import { SocketIssueSeverity } from './SocketIssueSeverity';
import { SocketRef } from './SocketRef';
import { HttpFile } from '../http/http';

export class SocketIssueBasics {
    'severity': SocketIssueSeverity;
    'category': SocketCategory;
    'locations': Array<SocketRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "severity",
            "baseName": "severity",
            "type": "SocketIssueSeverity",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "SocketCategory",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<SocketRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketIssueBasics.attributeTypeMap;
    }

    public constructor() {
    }
}

