/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRefByteRange } from './SocketRefByteRange';
import { SocketRefTextRange } from './SocketRefTextRange';
import { HttpFile } from '../http/http';

export class SocketRefFile {
    'path': string;
    'range'?: SocketRefTextRange;
    'bytes'?: SocketRefByteRange;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "SocketRefTextRange",
            "format": ""
        },
        {
            "name": "bytes",
            "baseName": "bytes",
            "type": "SocketRefByteRange",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRefFile.attributeTypeMap;
    }

    public constructor() {
    }
}

