/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketLicenseScoreComponents } from './SocketLicenseScoreComponents';
import { HttpFile } from '../http/http';

export class SocketLicenseScore {
    'score': number;
    'components': SocketLicenseScoreComponents;
    'limit'?: number;
    'limitingMetric'?: SocketLicenseScoreLimitingMetricEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "SocketLicenseScoreComponents",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "limitingMetric",
            "baseName": "limitingMetric",
            "type": "SocketLicenseScoreLimitingMetricEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketLicenseScore.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketLicenseScoreLimitingMetricEnum = "0" | "1" | "2" | "3" | "4" ;

