/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketLicenseScoreComponentsLicenseQuality } from './SocketLicenseScoreComponentsLicenseQuality';
import { SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow } from './SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow';
import { HttpFile } from '../http/http';

export class SocketLicenseScoreComponents {
    'licenseIssueLow': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'licenseIssueMid': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'licenseIssueHigh': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'licenseIssueCritical': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'licenseQuality': SocketLicenseScoreComponentsLicenseQuality;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "licenseIssueLow",
            "baseName": "licenseIssueLow",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "licenseIssueMid",
            "baseName": "licenseIssueMid",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "licenseIssueHigh",
            "baseName": "licenseIssueHigh",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "licenseIssueCritical",
            "baseName": "licenseIssueCritical",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "licenseQuality",
            "baseName": "licenseQuality",
            "type": "SocketLicenseScoreComponentsLicenseQuality",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketLicenseScoreComponents.attributeTypeMap;
    }

    public constructor() {
    }
}

