/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRef } from './SocketRef';
import { SocketRefFile } from './SocketRefFile';
import { HttpFile } from '../http/http';

export class SocketUsageRef {
    'file': SocketRefFile;
    'dependencies': Array<SocketRef>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "file",
            "baseName": "file",
            "type": "SocketRefFile",
            "format": ""
        },
        {
            "name": "dependencies",
            "baseName": "dependencies",
            "type": "Array<SocketRef>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketUsageRef.attributeTypeMap;
    }

    public constructor() {
    }
}

