/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketMiscellaneousScoreComponentsDefaultBranch } from './SocketMiscellaneousScoreComponentsDefaultBranch';
import { SocketMiscellaneousScoreComponentsRepoCreatedAt } from './SocketMiscellaneousScoreComponentsRepoCreatedAt';
import { SocketMiscellaneousScoreComponentsTypeModule } from './SocketMiscellaneousScoreComponentsTypeModule';
import { HttpFile } from '../http/http';

export class SocketMiscellaneousScoreComponents {
    'typeModule': SocketMiscellaneousScoreComponentsTypeModule;
    'defaultBranch'?: SocketMiscellaneousScoreComponentsDefaultBranch;
    'repoCreatedAt'?: SocketMiscellaneousScoreComponentsRepoCreatedAt;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "typeModule",
            "baseName": "typeModule",
            "type": "SocketMiscellaneousScoreComponentsTypeModule",
            "format": ""
        },
        {
            "name": "defaultBranch",
            "baseName": "defaultBranch",
            "type": "SocketMiscellaneousScoreComponentsDefaultBranch",
            "format": ""
        },
        {
            "name": "repoCreatedAt",
            "baseName": "repoCreatedAt",
            "type": "SocketMiscellaneousScoreComponentsRepoCreatedAt",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketMiscellaneousScoreComponents.attributeTypeMap;
    }

    public constructor() {
    }
}

