/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketIssueAnyOf } from './SocketIssueAnyOf';
import { SocketIssueAnyOf1 } from './SocketIssueAnyOf1';
import { SocketIssueAnyOf10 } from './SocketIssueAnyOf10';
import { SocketIssueAnyOf11 } from './SocketIssueAnyOf11';
import { SocketIssueAnyOf12 } from './SocketIssueAnyOf12';
import { SocketIssueAnyOf13 } from './SocketIssueAnyOf13';
import { SocketIssueAnyOf14 } from './SocketIssueAnyOf14';
import { SocketIssueAnyOf15 } from './SocketIssueAnyOf15';
import { SocketIssueAnyOf16 } from './SocketIssueAnyOf16';
import { SocketIssueAnyOf17 } from './SocketIssueAnyOf17';
import { SocketIssueAnyOf18 } from './SocketIssueAnyOf18';
import { SocketIssueAnyOf19 } from './SocketIssueAnyOf19';
import { SocketIssueAnyOf2 } from './SocketIssueAnyOf2';
import { SocketIssueAnyOf20 } from './SocketIssueAnyOf20';
import { SocketIssueAnyOf21 } from './SocketIssueAnyOf21';
import { SocketIssueAnyOf22 } from './SocketIssueAnyOf22';
import { SocketIssueAnyOf23 } from './SocketIssueAnyOf23';
import { SocketIssueAnyOf24 } from './SocketIssueAnyOf24';
import { SocketIssueAnyOf25 } from './SocketIssueAnyOf25';
import { SocketIssueAnyOf26 } from './SocketIssueAnyOf26';
import { SocketIssueAnyOf27 } from './SocketIssueAnyOf27';
import { SocketIssueAnyOf28 } from './SocketIssueAnyOf28';
import { SocketIssueAnyOf29 } from './SocketIssueAnyOf29';
import { SocketIssueAnyOf3 } from './SocketIssueAnyOf3';
import { SocketIssueAnyOf30 } from './SocketIssueAnyOf30';
import { SocketIssueAnyOf31 } from './SocketIssueAnyOf31';
import { SocketIssueAnyOf32 } from './SocketIssueAnyOf32';
import { SocketIssueAnyOf33 } from './SocketIssueAnyOf33';
import { SocketIssueAnyOf34 } from './SocketIssueAnyOf34';
import { SocketIssueAnyOf35 } from './SocketIssueAnyOf35';
import { SocketIssueAnyOf36 } from './SocketIssueAnyOf36';
import { SocketIssueAnyOf37 } from './SocketIssueAnyOf37';
import { SocketIssueAnyOf38 } from './SocketIssueAnyOf38';
import { SocketIssueAnyOf39 } from './SocketIssueAnyOf39';
import { SocketIssueAnyOf4 } from './SocketIssueAnyOf4';
import { SocketIssueAnyOf40 } from './SocketIssueAnyOf40';
import { SocketIssueAnyOf41 } from './SocketIssueAnyOf41';
import { SocketIssueAnyOf42 } from './SocketIssueAnyOf42';
import { SocketIssueAnyOf43 } from './SocketIssueAnyOf43';
import { SocketIssueAnyOf44 } from './SocketIssueAnyOf44';
import { SocketIssueAnyOf45 } from './SocketIssueAnyOf45';
import { SocketIssueAnyOf46 } from './SocketIssueAnyOf46';
import { SocketIssueAnyOf47 } from './SocketIssueAnyOf47';
import { SocketIssueAnyOf48 } from './SocketIssueAnyOf48';
import { SocketIssueAnyOf49 } from './SocketIssueAnyOf49';
import { SocketIssueAnyOf5 } from './SocketIssueAnyOf5';
import { SocketIssueAnyOf50 } from './SocketIssueAnyOf50';
import { SocketIssueAnyOf51 } from './SocketIssueAnyOf51';
import { SocketIssueAnyOf52 } from './SocketIssueAnyOf52';
import { SocketIssueAnyOf53 } from './SocketIssueAnyOf53';
import { SocketIssueAnyOf54 } from './SocketIssueAnyOf54';
import { SocketIssueAnyOf55 } from './SocketIssueAnyOf55';
import { SocketIssueAnyOf56 } from './SocketIssueAnyOf56';
import { SocketIssueAnyOf57 } from './SocketIssueAnyOf57';
import { SocketIssueAnyOf58 } from './SocketIssueAnyOf58';
import { SocketIssueAnyOf59 } from './SocketIssueAnyOf59';
import { SocketIssueAnyOf6 } from './SocketIssueAnyOf6';
import { SocketIssueAnyOf60 } from './SocketIssueAnyOf60';
import { SocketIssueAnyOf61 } from './SocketIssueAnyOf61';
import { SocketIssueAnyOf62 } from './SocketIssueAnyOf62';
import { SocketIssueAnyOf63 } from './SocketIssueAnyOf63';
import { SocketIssueAnyOf64 } from './SocketIssueAnyOf64';
import { SocketIssueAnyOf65 } from './SocketIssueAnyOf65';
import { SocketIssueAnyOf66 } from './SocketIssueAnyOf66';
import { SocketIssueAnyOf67 } from './SocketIssueAnyOf67';
import { SocketIssueAnyOf68 } from './SocketIssueAnyOf68';
import { SocketIssueAnyOf69 } from './SocketIssueAnyOf69';
import { SocketIssueAnyOf7 } from './SocketIssueAnyOf7';
import { SocketIssueAnyOf70 } from './SocketIssueAnyOf70';
import { SocketIssueAnyOf71 } from './SocketIssueAnyOf71';
import { SocketIssueAnyOf8 } from './SocketIssueAnyOf8';
import { SocketIssueAnyOf9 } from './SocketIssueAnyOf9';
import { SocketIssueBasics } from './SocketIssueBasics';
import { SocketUsageRef } from './SocketUsageRef';
import { HttpFile } from '../http/http';

export class SocketIssue {
    'type'?: SocketIssueTypeEnum;
    'value'?: SocketIssueBasics & any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SocketIssueTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketIssueBasics & any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketIssue.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketIssueTypeEnum = "troll" ;

