/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type SocketLicenseQuality = "model" | "gold" | "silver" | "bronze" | "lead" | "nonfree" | "unknown" | "unlicensed" ;
