/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRefWeb } from './SocketRefWeb';
import { HttpFile } from '../http/http';

export class SocketRefAnyOf3 {
    'type'?: SocketRefAnyOf3TypeEnum;
    'value'?: SocketRefWeb;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SocketRefAnyOf3TypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketRefWeb",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRefAnyOf3.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketRefAnyOf3TypeEnum = "web" ;

