/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRefNPM } from './SocketRefNPM';
import { HttpFile } from '../http/http';

export class SocketRefAnyOf1 {
    'type'?: SocketRefAnyOf1TypeEnum;
    'value'?: SocketRefNPM;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SocketRefAnyOf1TypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketRefNPM",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRefAnyOf1.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketRefAnyOf1TypeEnum = "npm" ;

