/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketLicenseScore } from './SocketLicenseScore';
import { SocketMaintenanceScore } from './SocketMaintenanceScore';
import { SocketMiscellaneousScore } from './SocketMiscellaneousScore';
import { SocketQualityScore } from './SocketQualityScore';
import { SocketSupplyChainScore } from './SocketSupplyChainScore';
import { SocketVulnerabilityScore } from './SocketVulnerabilityScore';
import { HttpFile } from '../http/http';

export class SocketPackageScore {
    'supplyChainRisk': SocketSupplyChainScore;
    'quality': SocketQualityScore;
    'maintenance': SocketMaintenanceScore;
    'vulnerability': SocketVulnerabilityScore;
    'license': SocketLicenseScore;
    'miscellaneous': SocketMiscellaneousScore;
    'depscore': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "supplyChainRisk",
            "baseName": "supplyChainRisk",
            "type": "SocketSupplyChainScore",
            "format": ""
        },
        {
            "name": "quality",
            "baseName": "quality",
            "type": "SocketQualityScore",
            "format": ""
        },
        {
            "name": "maintenance",
            "baseName": "maintenance",
            "type": "SocketMaintenanceScore",
            "format": ""
        },
        {
            "name": "vulnerability",
            "baseName": "vulnerability",
            "type": "SocketVulnerabilityScore",
            "format": ""
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "SocketLicenseScore",
            "format": ""
        },
        {
            "name": "miscellaneous",
            "baseName": "miscellaneous",
            "type": "SocketMiscellaneousScore",
            "format": ""
        },
        {
            "name": "depscore",
            "baseName": "depscore",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketPackageScore.attributeTypeMap;
    }

    public constructor() {
    }
}

