/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketLicenseQuality } from './SocketLicenseQuality';
import { HttpFile } from '../http/http';

export class SocketLicenseScoreComponentsLicenseQuality {
    'score': number;
    'maxScore': number;
    'limit': number;
    'value': SocketLicenseQuality;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxScore",
            "baseName": "maxScore",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketLicenseQuality",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketLicenseScoreComponentsLicenseQuality.attributeTypeMap;
    }

    public constructor() {
    }
}

