/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SocketRefTextRange {
    'startLine': number;
    'startColumn': number;
    'endLine': number;
    'endColumn': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "startLine",
            "baseName": "startLine",
            "type": "number",
            "format": ""
        },
        {
            "name": "startColumn",
            "baseName": "startColumn",
            "type": "number",
            "format": ""
        },
        {
            "name": "endLine",
            "baseName": "endLine",
            "type": "number",
            "format": ""
        },
        {
            "name": "endColumn",
            "baseName": "endColumn",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRefTextRange.attributeTypeMap;
    }

    public constructor() {
    }
}

