/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRefGit } from './SocketRefGit';
import { HttpFile } from '../http/http';

export class SocketRefAnyOf2 {
    'type'?: SocketRefAnyOf2TypeEnum;
    'value'?: SocketRefGit;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SocketRefAnyOf2TypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketRefGit",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRefAnyOf2.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketRefAnyOf2TypeEnum = "git" ;

