/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketIssueBasics } from './SocketIssueBasics';
import { SocketUsageRef } from './SocketUsageRef';
import { HttpFile } from '../http/http';

export class SocketIssueAnyOf {
    'type'?: SocketIssueAnyOfTypeEnum;
    'value'?: SocketIssueBasics & any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SocketIssueAnyOfTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketIssueBasics & any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketIssueAnyOf.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketIssueAnyOfTypeEnum = "criticalCVE" ;

