/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRefFile } from './SocketRefFile';
import { HttpFile } from '../http/http';

export class SocketRefWeb {
    'url': string;
    'file'?: SocketRefFile;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "SocketRefFile",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRefWeb.attributeTypeMap;
    }

    public constructor() {
    }
}

