/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketIssue } from './SocketIssue';
import { SocketReportDependency } from './SocketReportDependency';
import { SocketReportScore } from './SocketReportScore';
import { HttpFile } from '../http/http';

export class SocketReport {
    'dependencies': Array<SocketReportDependency>;
    'issues': Array<SocketIssue>;
    'score': SocketReportScore;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dependencies",
            "baseName": "dependencies",
            "type": "Array<SocketReportDependency>",
            "format": ""
        },
        {
            "name": "issues",
            "baseName": "issues",
            "type": "Array<SocketIssue>",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "SocketReportScore",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketReport.attributeTypeMap;
    }

    public constructor() {
    }
}

