/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketRefAnyOf } from './SocketRefAnyOf';
import { SocketRefAnyOf1 } from './SocketRefAnyOf1';
import { SocketRefAnyOf2 } from './SocketRefAnyOf2';
import { SocketRefAnyOf3 } from './SocketRefAnyOf3';
import { SocketRefWeb } from './SocketRefWeb';
import { HttpFile } from '../http/http';

export class SocketRef {
    'type'?: SocketRefTypeEnum;
    'value'?: SocketRefWeb;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SocketRefTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "SocketRefWeb",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketRef.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SocketRefTypeEnum = "web" ;

