/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SocketReportScore {
    'avgSupplyChainRisk': number;
    'avgQuality': number;
    'avgMaintenance': number;
    'avgVulnerability': number;
    'avgLicense': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "avgSupplyChainRisk",
            "baseName": "avgSupplyChainRisk",
            "type": "number",
            "format": ""
        },
        {
            "name": "avgQuality",
            "baseName": "avgQuality",
            "type": "number",
            "format": ""
        },
        {
            "name": "avgMaintenance",
            "baseName": "avgMaintenance",
            "type": "number",
            "format": ""
        },
        {
            "name": "avgVulnerability",
            "baseName": "avgVulnerability",
            "type": "number",
            "format": ""
        },
        {
            "name": "avgLicense",
            "baseName": "avgLicense",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketReportScore.attributeTypeMap;
    }

    public constructor() {
    }
}

