/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow } from './SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow';
import { HttpFile } from '../http/http';

export class SocketQualityScoreComponents {
    'qualityIssueLow': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'qualityIssueMid': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'qualityIssueHigh': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'qualityIssueCritical': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'linesOfCode': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'readmeLength': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'bundlesize'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'stargazers'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'forks'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'watchers'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "qualityIssueLow",
            "baseName": "qualityIssueLow",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "qualityIssueMid",
            "baseName": "qualityIssueMid",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "qualityIssueHigh",
            "baseName": "qualityIssueHigh",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "qualityIssueCritical",
            "baseName": "qualityIssueCritical",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "linesOfCode",
            "baseName": "linesOfCode",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "readmeLength",
            "baseName": "readmeLength",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "bundlesize",
            "baseName": "bundlesize",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "stargazers",
            "baseName": "stargazers",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "forks",
            "baseName": "forks",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "watchers",
            "baseName": "watchers",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketQualityScoreComponents.attributeTypeMap;
    }

    public constructor() {
    }
}

