/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow } from './SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow';
import { HttpFile } from '../http/http';

export class SocketSupplyChainScoreComponents {
    'supplyChainRiskIssueLow': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'supplyChainRiskIssueMid': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'supplyChainRiskIssueHigh': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'supplyChainRiskIssueCritical': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'dependencyCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'devDependencyCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'unusedDependencyCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'transitiveDependencyCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'totalDependencyCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'downloadCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "supplyChainRiskIssueLow",
            "baseName": "supplyChainRiskIssueLow",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "supplyChainRiskIssueMid",
            "baseName": "supplyChainRiskIssueMid",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "supplyChainRiskIssueHigh",
            "baseName": "supplyChainRiskIssueHigh",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "supplyChainRiskIssueCritical",
            "baseName": "supplyChainRiskIssueCritical",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "dependencyCount",
            "baseName": "dependencyCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "devDependencyCount",
            "baseName": "devDependencyCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "unusedDependencyCount",
            "baseName": "unusedDependencyCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "transitiveDependencyCount",
            "baseName": "transitiveDependencyCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "totalDependencyCount",
            "baseName": "totalDependencyCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "downloadCount",
            "baseName": "downloadCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketSupplyChainScoreComponents.attributeTypeMap;
    }

    public constructor() {
    }
}

