/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow } from './SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow';
import { HttpFile } from '../http/http';

export class SocketMaintenanceScoreComponents {
    'maintenanceIssueLow': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'maintenanceIssueMid': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'maintenanceIssueHigh': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'maintenanceIssueCritical': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'maintainerCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'versionsLastWeek': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'versionsLastMonth': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'versionsLastTwoMonths': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'versionsLastYear': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'versionCount': SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'openIssues'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'closedIssues'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'commitsLastWeek'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'commitsLastMonth'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'commitsLastTwoMonths'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'commitsLastYear'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;
    'commits'?: SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maintenanceIssueLow",
            "baseName": "maintenanceIssueLow",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "maintenanceIssueMid",
            "baseName": "maintenanceIssueMid",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "maintenanceIssueHigh",
            "baseName": "maintenanceIssueHigh",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "maintenanceIssueCritical",
            "baseName": "maintenanceIssueCritical",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "maintainerCount",
            "baseName": "maintainerCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "versionsLastWeek",
            "baseName": "versionsLastWeek",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "versionsLastMonth",
            "baseName": "versionsLastMonth",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "versionsLastTwoMonths",
            "baseName": "versionsLastTwoMonths",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "versionsLastYear",
            "baseName": "versionsLastYear",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "versionCount",
            "baseName": "versionCount",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "openIssues",
            "baseName": "openIssues",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "closedIssues",
            "baseName": "closedIssues",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "commitsLastWeek",
            "baseName": "commitsLastWeek",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "commitsLastMonth",
            "baseName": "commitsLastMonth",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "commitsLastTwoMonths",
            "baseName": "commitsLastTwoMonths",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "commitsLastYear",
            "baseName": "commitsLastYear",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        },
        {
            "name": "commits",
            "baseName": "commits",
            "type": "SocketSupplyChainScoreComponentsSupplyChainRiskIssueLow",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketMaintenanceScoreComponents.attributeTypeMap;
    }

    public constructor() {
    }
}

