/**
 * Socket API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocketPackageScore } from './SocketPackageScore';
import { SocketUsageRef } from './SocketUsageRef';
import { HttpFile } from '../http/http';

export class SocketReportDependency {
    '_package': string;
    'version': string;
    'usage': SocketUsageRef;
    'score': SocketPackageScore;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_package",
            "baseName": "package",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "SocketUsageRef",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "SocketPackageScore",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SocketReportDependency.attributeTypeMap;
    }

    public constructor() {
    }
}

